// Gamaka draw page. Opens the current composition (localStorage, or a shared
// #pako link) as a pitch/time roll and lets the user draw a pitch curve per note.
// Pitch is 53-EDO (22-shruti): notes sit on their default shruti, snap targets
// the 22 shrutis, audio is microtonal. Curves + the srgm source pack into a
// #pako link (melody + gamakas).
import { parse, TALA_MAP } from './core/parser.js';
import { setRagas, getRagas, resolveRagaName } from './core/raga-base.js';
import { setRagaExt, getRagaExt } from './core/raga-ext.js';
import { chooseSeed, loadDrafts } from './core/raga-seed.js';
import { midiToFreq } from './audio/schedule.js';
import { BOXES, EDO, stepFreq } from './core/shruti.js';
import { encodeShareToken, decodeShareToken } from './core/share.js';
import { VERSION, BUILD_DATE } from './version.js';
import { midiToName } from './core/tuning.js';
import { serializeInline, sampleCurve } from './core/gamaka-inline.js';
import { buildRollModel } from './core/roll-model.js';
import { createRagamRoll } from './core/ragamroll.js';
import { createRollAudio } from './core/roll-audio.js';
import { createRollEdit } from './core/roll-edit.js';
import { anchorsOf, resplitAt } from './core/note-split.js';
import { createSeamHost } from './core/roll-seam.js';
import { pointsToAnchors, addAnchor, removeAnchor, moveAnchor } from './core/gamaka-curve.js';
import { createCurveEdit } from './core/curve-edit.js';
import { createGamakaEdit } from './core/gamaka-edit.js';
import { createGridStretch } from './core/grid-stretch.js';
import { buildSequence } from './core/midi/sequence.js';
import { writeSMF } from './core/midi/smf.js';
import { serializeModel, applyEdit, applyMove, paintEdit, snapToRagaRow, snapToAkshara, placePaint, splitSpans, octMarks } from './core/note-edit.js';
import { buildRagaSteps } from './core/detect-raga-helper.js';
// Aliased: shruti.js exports a DIFFERENT stepForLetter(scale, letter). This one
// is (letter, approxStep, ragaSwaraName) -> the raga's own step for that letter.
import { stepToSwara } from './core/detect.js';

const LS_KEY = 'ragamroll.srgm';
const SHRUTI = [...new Set(BOXES.map(b => b.step))].sort((a, b) => a - b);   // 22 steps in an octave

// ---------- model built from the parsed composition ----------
let NOTES = [];        // [{step, dur, swara, octave, curve:null|[[u,step]...]}]
let saRef = 60, saFreq = midiToFreq(60), tempoBpm = 120, TOTAL = 0;
let saPlay = null;     // Sa reference-pitch override (midi); null = auto (= saRef, the layout anchor)
let compTempo = 120;   // the composition's own tempo; the tempo slider is a multiplier of this
let starts = [], RESTS = [], selRest = -1, gridPitches = [], stepMin = -26, stepMax = 66, srcText = '';
let contentEnd = 0;   // true content end from buildModel's starts-loop cursor `t` (rests included; 0 for a blank piece)
let userGridMin = null, userGridMax = null, userGridBottom = null;  // handle-stretched roll bounds (view-state, NOT saved)
let talaMeasure = 0, talaAccents = [], talaBeat = 0;   // cycle length + 1-based accent slots + akshara length (length-units)
let docName = 'ragamroll';               // base filename for Save / Export MIDI
let curRaga = '', curTala = '', curTalaName = 'adi';   // readout + current tala name (for the picker)
let defaultRaga = 'c12';                                 // set at boot to the first raga in the picker list
const blankSrc = () => `Raga=${defaultRaga},0\nTala=adi,4\nO=5 L=1\n`;   // Blank/New skeleton (no notes)

// Everything the parser could not honour, shown where the piece is. The parser
// has always recorded these -- a dropped gamaka arrives as "malformed attributes
// ... playing the plain note" -- but only index.html ever displayed them, so in
// draw a corrupted gamaka silently became a plain note and the notation looked
// fine. Silence is the bug: the note still plays, just not as written.
function reportDiagnostics(model, generated){
  const el = document.getElementById('parsewarn');
  if (!el) return;
  const ds = (model && model.diagnostics) || [];
  if (!ds.length) { el.style.display = 'none'; el.innerHTML = ''; return; }
  el.innerHTML = '<button type="button">dismiss</button><b>' + (generated
    ? 'This notation was generated by RagaM-Roll and cannot be read back — that is a bug, please report it.'
    : ds.length + ' part(s) of this notation could not be read as written.') +
    '</b> What is playing instead:<ul>' +
    ds.map(d => `<li>${d.message.replace(/[<&]/g, c => ({'<':'&lt;','&':'&amp;'}[c]))}</li>`).join('') +
    '</ul>';
  el.querySelector('button').onclick = () => { el.style.display = 'none'; };
  el.style.display = '';
}

// Notation in, roll out. The derivation itself lives in core/roll-model.js so the
// library page and the app read a piece the same way draw does; what stays here is
// draw's own state around it — the tempo slider's baseline, the Sa override, the
// segment markers, the name the tala dialog shows.
function buildModel(src){
  srcText = src || '';
  const model = parse(srcText);
  reportDiagnostics(model);
  const m = buildRollModel(model);
  roll.setModel(m);
  NOTES = m.notes; starts = m.starts; RESTS = m.rests; contentEnd = m.contentEnd;
  if (!RESTS.some((r) => r.tok === selRest)) selRest = -1;   // the selected rest may not have survived the edit
  compTempo = m.tempo;
  tempoBpm = compTempo;   // reset to the composition tempo on (re)load; the slider re-applies its multiplier
  saRef = m.saRef;
  saPlay = null;          // reset Sa override to auto on a new composition
  saFreq = midiToFreq(saRef);   // saRef is the LAYOUT anchor (steps); saPlay only retunes playback
  curRaga = m.raga;
  talaMeasure = m.tala.measure; talaAccents = m.tala.accents; talaBeat = m.tala.beat;
  curTala = m.talaProps ? `beat ${m.talaProps.beat}` : '';
  curTalaName = (srcText.match(/(?:^|\s)Tala=([A-Za-z0-9]+)/) || [])[1] || 'adi';
  recomputeGridBounds();
  markerA = 0; markerB = TOTAL;   // segment bounds default to the whole piece; draggable in the gutter
}
// Recompute TOTAL/stepMin/stepMax/gridPitches from the current NOTES/starts/
// talaMeasure/curRaga/userGrid* module state. Pulled out of buildModel's tail so a
// live handle-stretch (userGrid* changed, nothing re-parsed) can re-derive the grid
// bounds without re-running the parser. Does NOT touch userGrid* itself — only
// loadSrc/applyShared reset those (new composition), same invariant as before.
function recomputeGridBounds(){
  roll.setUser({ min:userGridMin, max:userGridMax, bottom:userGridBottom });
  const b = roll.bounds();
  TOTAL = b.total; stepMin = b.stepMin; stepMax = b.stepMax; gridPitches = b.gridPitches;
}
const freqOf = step => stepFreq(saFreq, step);
const secPerUnit = () => 30 / tempoBpm;

// ---------- canvas ----------
const cv = document.getElementById('cv');
let mode='roll', sel=-1, drawSpan=22;   // the curve gesture's own state lives in core/curve-edit.js
// Roll-mode long-press grab (move/resize a note). paintMode is wired to the
// `+ note` toolbar toggle below; grab and paint gestures are mutually exclusive.
let paintMode=false, gamakaMode=false;   // the press/drag gestures themselves live in core/roll-edit.js
const HANDLE_PX=18;
const ROLL_TOUCH_ACTION='pan-y';   // touchAction roll mode uses when idle (matches resizeCanvas below)
// The grid stretch-handles are core/grid-stretch.js's gesture and core/roll-render.js's
// drawing now, so the app widens the same grid the same way. What used to be here was
// two copies of the tab arithmetic — one to draw, one to hit-test — each with a comment
// saying it must match the other.
let zoom = 1;   // expand multiplier the roll scales time by (1 = shortest note cell at its minimum readable height)
const yVirt = t => { syncView(); return roll.yVirt(t); };   // roll virtual y (content coords, pre-scroll) — the gutter handles sit at these
const pxU = () => { syncView(); return roll.pxPerUnit(); };   // pixels per length-unit
const virtH = () => { syncView(); return roll.virtH(); };     // full scroll height of the roll
let playing=false, paused=false, playStart=0, rafId=0, playPos=null;   // playhead (length-units)
let playFromU=0, playToU=0, pausedAt=0, pausedTo=0;                    // playback range + pause point
let markerA=0, markerB=0, ctxTime=0, markerDrag=null;                 // A–B segment markers (length-units) + drag state
const cssvar = k => getComputedStyle(document.documentElement).getPropertyValue(k).trim();
// The roll itself — canvas, sizing, the scroll window, the grid it derives. draw
// supplies the palette and its editing chrome and keeps everything else: the audio,
// the transport, the notation, and every gesture that changes a note.
const roll = createRagamRoll({ holder: document.getElementById('holder'), content: document.getElementById('content'), canvas: cv }, {
  touchAction: ROLL_TOUCH_ACTION,
  palette: () => ({ amber:cssvar('--amber'), amberS:cssvar('--amberSoft'), teal:cssvar('--teal'),
    terra:cssvar('--terra'), hair:cssvar('--hair2'), muted:cssvar('--muted'),
    panel2:cssvar('--panel2'), mono:cssvar('--mono'), bg:cssvar('--bg'), sans:cssvar('--sans') }),
  hooks: { underGrid: drawRestGutter, overNotes: drawEditChrome },
});
const ctx = roll.ctx, PAD = roll.pad;
// Hit-testing reads the coordinates the roll actually drew with, so a note cannot be
// visible in one place and grabbable in another.
function geo(){ syncView(); return roll.geometry(); }
const plot = () => geo().plot;
function X(s){ return geo().X(s); }
function stepAtX(px){ return geo().stepAtX(px); }
function yStartEnd(){ return geo().yRange; }
function Y(t){ return geo().Y(t); }
function tAtY(py){ return geo().tAtY(py); }

function fit(){ const h=(window.visualViewport&&window.visualViewport.height)||window.innerHeight;
  document.getElementById('wrap').style.height=h+'px'; requestAnimationFrame(resizeCanvas); }
function resizeCanvas(){ syncView(); roll.resize(); positionHandles(); if (mode==='roll') restoreView(); }

// Where the roll is looking, held as a TIME rather than as a scroll offset.
//
// scrollTop is pixels, and pixels-per-unit is derived from the SHORTEST note in the
// piece — split one note and the whole time axis rescales underneath you. Keeping the
// pixel then puts you somewhere else in the music, which reads as the grid having
// jumped on its own; keeping the time puts you back on the same phrase. Measured: a
// split took the scroll range from 186px to 762px with scrollTop untouched at 102.
//
// Everything that rebuilds the grid goes through resizeCanvas(), so that is the one
// place this has to happen: every edit that re-serialises the piece, the zoom buttons,
// a window resize, and the return from the curve editor — which collapses the scroll
// height to a single screen, so the browser clamps scrollTop to 0 on the way IN and
// there is nothing left to come back to.
// null means "nothing remembered yet" — go to the top. It has to be its own value
// rather than the time 0, because t=0 sits BELOW the header pad: mapping 0 back would
// park a freshly opened piece 44px down, and clamping the remembered time at 0 instead
// would make the mapping one-way and lose the pad strip entirely. Times above the first
// note are simply negative.
let viewT = null;
function rememberView(){ const hd=$('holder'), u=pxU(); if (u>0) viewT = (hd.scrollTop - PAD.t)/u; }
function restoreView(){ const hd=$('holder'), u=pxU();
  if (viewT === null || !(u>0)) { hd.scrollTop = 0; return; }
  hd.scrollTop = Math.max(0, Math.min(Math.max(0, virtH()-hd.clientHeight), PAD.t + viewT*u));
  // Read back what the browser actually allowed and keep THAT. Near the end of a piece
  // the target is clamped, and holding the unreachable time instead would make the
  // next rebuild jump again the moment the piece grew.
  rememberView(); }

// draw's state, pushed into the roll before anything reads or draws it. The roll is
// told what to show; it never reaches back for it.
function syncView(){
  roll.setView({ mode, sel, selRest, drawSpan, zoom, playPos, markerA, markerB,
    saMidi: saPlay==null ? saRef : saPlay, grabIdx: rollEdit ? rollEdit.grabbedIndex() : -1,
    // The rest gutter and the in-progress paint box are the shared renderer's now, so
    // they are told rather than drawn here — both apps aim at the same band.
    paintMode: mode==='roll' && paintMode, paint: rollEdit ? rollEdit.painting() : null,
    drawing: curveEdit ? curveEdit.drawing() : false, gamakaMode: mode==='roll' && gamakaMode,
    // The stretch tabs, drawn by the shared renderer now. Roll mode only: the one-note
    // layout has no grid to widen.
    handles: mode==='roll' });
}
// ---- editing chrome ----
// Painted through the roll's hooks, because it is interleaved with the roll's own
// layers rather than sitting on top: the rest gutter goes under the pitch lines, the
// gamaka anchors over the notes but under the segment markers. Each hook is handed
// the geometry, so the chrome and the roll cannot disagree about where anything is.
function drawRestGutter(g){ const p=g.plot, [sa,sb]=g.xRange, C=roll.ctx;
  // A faint band at the left edge, paint mode only — pressing inside it paints a rest
  // Draw mode zooms onto one note and shows every shruti — you are placing a pitch by
  // hand there, not reading a raga.
  if (mode==='draw'){ for (let oct=Math.floor(sa/EDO)-1; oct<=Math.floor(sb/EDO)+1; oct++) for (const sh of SHRUTI){ const s=oct*EDO+sh;
    if (s<sa||s>sb) continue; const x=g.X(s); C.strokeStyle=cssvar('--hair2'); C.globalAlpha=.5; C.beginPath(); C.moveTo(x,p.y); C.lineTo(x,p.y+p.h); C.stroke(); C.globalAlpha=1; } }
}
function drawEditChrome(g){ const p=g.plot, X=g.X, Y=g.Y, C=roll.ctx, teal=cssvar('--teal');
  // In-roll gamaka anchors are the shared renderer's now.
  // The curve editor's anchors and its empty-note prompt are the shared renderer's now.
}
function render(){ syncView(); roll.render(); positionHandles(); }
// Position the draggable A/B gutter handles at their marker times. The gutter is
// absolute-in-content (scrolls with the roll), so handles sit at VIRTUAL y and stay
// aligned with their marker lines as you scroll.
function positionHandles(){ const g=$('gutter'); if (mode!=='roll'){ g.style.display='none'; return; } g.style.display='';
  $('mkA').style.top=yVirt(markerA)+'px'; $('mkB').style.top=yVirt(markerB)+'px'; }

// ---------- interaction ----------
function evtPos(e){ const r=cv.getBoundingClientRect(); return { x:e.clientX-r.left, y:e.clientY-r.top }; }
// roll: selection is a click/tap (so a drag can scroll the tall roll)
const DEDIT_EPS=6;
// Is (x,y) on the selected note's curve LINE (draw-mode coords), for tap-to-add?
// The curve-editor gestures live in core/curve-edit.js — the third gesture module, and
// framework-free like the others, so the app can mount the same editor. What stays here
// is what a stroke COSTS draw: undo, the live tone, the Hz readout, its buttons, and
// re-serialising the notation.
const curveEdit = createCurveEdit(cv, {
  geometry: () => geo(),
  curve: () => (sel >= 0 && NOTES[sel] ? NOTES[sel].curve : null),
  setCurve: (c) => { if (sel >= 0 && NOTES[sel]) NOTES[sel].curve = c; syncCurveButtons(); },
  snapping: () => $('snap').checked,
  enabled: () => mode === 'draw',
  redraw: () => render(),
  sample: sampleCurve,
  onGrabStart: () => ensureAudio(),
  onPitch: (st, start) => {
    if (st == null) { liveOff(); $('read').textContent = ''; return; }
    if (start) liveOn();
    liveSet(st); $('read').textContent = '≈' + freqOf(st).toFixed(0) + ' Hz';
  },
  emit: (it) => {
    if (it.phase === 'begin') { pushUndo(); liveOn(); return; }
    autoPlay(); scheduleShare();
  },
});
function syncCurveButtons(){ const has = !!(sel >= 0 && NOTES[sel] && NOTES[sel].curve && NOTES[sel].curve.length);
  $('clear').disabled = !has; $('copy').disabled = !has; }

// The pointer gestures live in core/roll-edit.js: it decides what a press MEANS and
// emits an intent. What an edit costs — undo, re-serialising the notation, rebuilding
// the model — is decided here, because that is draw's answer and not every host's.
//
// preview: in flight, shown but not recorded. commit: recorded. cancel: put it back.
const rollEdit = createRollEdit(cv, {
  // Listening on #content, not on the canvas: the margin strip over it is a sibling of
  // the canvas and forbids panning, and a press there has to reach the same gestures.
  surface: document.getElementById('content'),
  geometry: () => geo(),
  model: () => ({ notes: NOTES, starts, rests: RESTS, stepMin, stepMax }),
  snapStep: (step) => snapToRagaRow(step, ragaRowSteps()),
  snapDur: (d) => { const beat = talaBeat || 1; return Math.max(beat, snapToAkshara(d, beat)); },
  snapTime: (t) => snapToAkshara(t, talaBeat || 1),
  marks: () => ({ a: markerA, b: markerB }),
  redraw: () => render(),
  enabled: () => mode === 'roll' && !gamakaMode,
  painting: () => paintMode,
  idleTouchAction: ROLL_TOUCH_ACTION,
  // The only scrolling a gesture may cause: an A–B sweep dragged past the top or bottom
  // of the window, so a range longer than the window can still be marked.
  scrollBy: (dy) => { const hd=document.getElementById('holder'); hd.scrollTop += dy; },
  onGrabStart: () => ensureAudio(),
  emit: (it) => applyIntent(it),
});

// Widening the grid: core/grid-stretch.js's gesture, hosted here. It resizes the VIEW,
// not the music, so nothing it emits is ever serialised — userGrid* are not saved and
// not shared.
const gridStretch = createGridStretch(cv, {
  geometry: () => geo(),
  size: () => roll.size(),
  bounds: () => ({ stepMin, stepMax, total: TOTAL }),
  snapStep: (step) => snapToRagaRow(step, ragaRowSteps()),
  snapTime: (t) => snapToAkshara(t, talaBeat||1),
  beat: () => talaBeat||1,
  measure: () => talaMeasure,
  enabled: () => mode==='roll' && !paintMode && !gamakaMode,
  idleTouchAction: ROLL_TOUCH_ACTION,
  redraw: () => render(),
  emit: (it) => {
    if (it.which==='pmin') userGridMin=it.step;
    else if (it.which==='pmax') userGridMax=it.step;
    else if (it.which==='bottom') userGridBottom=it.bottom;
    else if (it.which==='extend') userGridBottom=(userGridBottom!=null?userGridBottom:TOTAL)+it.by;
    recomputeGridBounds();
    const hd=document.getElementById('holder'), content=document.getElementById('content');
    content.style.height=virtH()+'px';
    // Keep the edge being pulled under the finger pulling it; on a tap, park the new
    // bottom near the viewport bottom so the tab is where the next tap will be.
    if (it.which==='bottom') hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), PAD.t + TOTAL*pxU() - it.y));
    else if (it.which==='extend'){ resizeCanvas(); hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), PAD.t + TOTAL*pxU() - (hd.clientHeight-40))); }
    render();
  },
});

// Whatever ends where this note begins — a note or a rest. Token order is the
// composition's order, rests included, so the neighbour is simply the highest tok
// below this one.
const seamHost = createSeamHost({
  model: () => ({ notes: NOTES, starts, rests: RESTS }),
  beat: () => talaBeat,
  pushUndo: () => pushUndo(),
  commit: (spec) => commitEdit(spec),
  render: () => render(),
  notify: (msg) => { $('mode').textContent = msg; },
});

const INTENT_LOG = [];              // headless guards read this; nothing else does
async function applyIntent(it) {
  INTENT_LOG.push({ ...it }); if (INTENT_LOG.length > 200) INTENT_LOG.shift();
  if (it.kind === 'select') {
    // A note and a rest are selected the same way now, into the two variables that
    // already existed. `sel` was previously set ONLY by opening the curve editor, so a
    // selected note is a new state on the roll — safe because every curve-editor
    // handler is gated on mode==='draw', and the renderer already draws v.sel with a
    // heavier border and its end caps.
    const t = it.target;
    selRest = t && t.type === 'rest' ? t.tok : -1;
    sel = t && t.type === 'note' ? t.index : -1;
    syncDelete(); render(); return;
  }
  if (it.kind === 'open') { selRest = -1; syncDelete(); enterDraw(it.index); return; }
  // Sweeping A–B in the margin. The gesture has been live here since roll-edit grew it,
  // but nothing was listening: the commit reads back the host's CURRENT marks to decide
  // whether a sweep is a range or a clear, and with no marks() and no handler every
  // sweep previewed correctly and then committed as {0,0}. A clear means the whole piece
  // here — this page has always used A=0, B=TOTAL for "no segment" rather than a
  // zero-length one.
  if (it.kind === 'range') {
    if (it.phase === 'commit' && !(it.b > it.a)) { markerA = 0; markerB = TOTAL; }
    else { markerA = it.a; markerB = it.b; }
    setPlayIdle(); render(); return;
  }
  if (it.kind === 'split') { await seamHost.handle(it); return; }
  if (it.kind === 'paint') {
    const place = placePaint({ ts: it.ts, dur: it.dur, notes: NOTES, starts, durs: NOTES.map((n) => n.dur), total: TOTAL });
    pushUndo(); await applyPaint(place, it); return;
  }

  const n = NOTES.find((x) => x.tok === it.tok);
  const r = RESTS.find((x) => x.tok === it.tok);

  if (it.kind === 'move') {
    if (!n) return;
    if (it.phase !== 'commit') { n.step = it.step; render(); return; }
    pushUndo(); await onMoveDrop(NOTES.indexOf(n), it.from);
    return;
  }
  // Both edges move the SEAM this note shares with its neighbour, and the sound across
  // the pair does not change. All of that lives in core/roll-seam.js now, so the app can
  // host the same drag; what stays here is undo, re-serialising and the redraw — the
  // things the two apps genuinely disagree about.
  if (it.kind === 'boundary') { await seamHost.handle(it); return; }
  // A rest's own edge — core/roll-seam.js, same as the seam drags.
  if (it.kind === 'resize') { await seamHost.handle(it); return; }
}

// Paint mode (`+ note` toggled on): drag on the grid creates a note — pitch snaps to
// a raga row, length to the tala akshara. Capture-phase + the !paintMode guard on the
// grab handlers above keep paint and grab gestures mutually exclusive. `paint` tracks
// its owning pointerId (`pid`), same pattern as `grab`, so a second concurrent touch
// can't overwrite the in-progress gesture and corrupt the eventual commit.
// Painting is core/roll-edit.js's gesture now, like every other press on the roll; what
// arrives here is the finished intent. The grid stretch-handles still get first refusal
// in the capture-phase listener above, so you can still zoom while painting is armed.
// In-roll gamaka editing (`✎ gamaka` toggled on) is core/gamaka-edit.js's gesture now,
// so the app can mount the same one. Grid handles and `+ time` are still checked first
// in the capture-phase listener above, so you can zoom while editing.
const gamakaEdit = createGamakaEdit(cv, {
  geometry: () => geo(),
  model: () => ({ notes: NOTES, starts }),
  hitNote: (x, y) => (mode === 'roll' && gamakaMode ? rollEdit.hitNote(x, y) : -1),
  snapping: () => $('snap').checked,
  enabled: () => mode === 'roll' && gamakaMode,
  redraw: () => render(),
  sample: sampleCurve,
  onGrabStart: () => ensureAudio(),
  emit: (it) => {
    if (it.phase === 'begin') { pushUndo(); return; }
    rollEdit.suppressClick();   // the trailing click must not open the full-screen editor
    scheduleShare();
  },
});
// Discoverability: hovering a stretch-handle shows a resize cursor (idle only — a cursor
// that changes mid-drag says the drag has been taken over).
cv.addEventListener('pointermove', e=>{ if (mode!=='roll' || gridStretch.busy() || rollEdit.busy()) return;
  const {x,y}=evtPos(e); const h=gridStretch.hit(x,y);
  cv.style.cursor = h ? (h==='bottom'?'pointer':'col-resize') : (paintMode?'crosshair':''); });
// A moved note is committed with the current gamaka-on-move default; if it carried
// a gamaka, a toast offers the other behaviour for ~4s. The model stores the curve
// ABSOLUTE, so 'preserve pitch' = leave the curve (serialize emits shifted relative
// deltas); 'move with note' = shift the abs curve by +Δstep so the relative deltas
// stay verbatim and the whole curve rides the note.
async function onMoveDrop(idx, oldStep){
  const n=NOTES[idx], dStep=n.step-oldStep;
  // Derive octave the same way the letter itself is derived (stepToSwara), not via
  // a raw Math.floor(step/EDO) — that disagrees with stepToSwara's c12 wrap-to-next-
  // octave behaviour near the top of an octave, which could spell the wrong octave.
  const ctx=ragaCtx();
  const hasCurve=!!(n.curve && n.curve.length);
  // Capture the mode once, before the await below — gmovesel can change live while
  // commitEdit is in flight, and the toast must describe/flip the mode that was
  // actually applied to this drop, not whatever the dropdown reads afterward.
  const appliedMode=gamakaOnMove;
  // The octave re-spelling and the gamaka's fate are shared with the app — see
  // core/note-edit.js. What stays here is the toast that lets the choice be flipped.
  const { deriveOctave }=applyMove(n, oldStep, ctx, appliedMode);
  await commitEdit({ changed:new Set([n.tok]), deriveOctave });
  if (!hasCurve) return;
  const other=appliedMode==='preserve-pitch'?'move-with-note':'preserve-pitch';
  const label=appliedMode==='preserve-pitch'?'move with note':'preserve pitch';
  showToast(`Gamaka: ${appliedMode==='preserve-pitch'?'pitch preserved':'moved with note'}`, `switch to ${label}`, async ()=>{
    // Flip: after buildModel, re-find the note by its tok and reshift the abs curve
    // by the opposite of what appliedMode implied, then re-commit.
    const j=NOTES.findIndex(x=>x.tok===n.tok); if (j<0) return; const m=NOTES[j];
    if (!m.curve || !m.curve.length) return;
    if (other==='move-with-note') m.curve=m.curve.map(([u,s])=>[u,s+dStep]);
    else m.curve=m.curve.map(([u,s])=>[u,s-dStep]);
    pushUndo(); await commitEdit({ changed:new Set([m.tok]), deriveOctave:false }); });
}
// Build the serializeModel insert for a painted note or rest. For 'split', the host
// is cut into a HEAD (kept by the host token) and a TAIL continuation (same pitch,
// inserted after the new item) via splitSpans — this preserves the host's original
// sustain instead of discarding it. For 'fill'/'append' the item lands at the
// DRAGGED time `p.ts`, not just after the anchor — a leading rest is inserted ahead
// of it whenever there's a time gap (append past the true content end, or fill/split
// before the very first note, via serializeModel's `inserts.get(-1)` prepend).
// What the notation must do about a painted note is core/note-edit.js's; what it costs
// — re-parsing, redrawing, the share link — is draw's, as with every other edit.
async function applyPaint(place, p){
  const spec = paintEdit({ place, ts:p.ts, dur:p.dur, step:p.step, rest:p.rest,
    model:modelByTok(), notes:NOTES, starts, contentEnd, ctx:ragaCtx() });
  if (spec.seed){
    buildModel(srcText.replace(/\s*$/,'') + '\n' + spec.seed + '\n');
    syncControls(); resizeCanvas(); render(); await rebuildShare(); return; }
  await commitEdit(spec);
}
// A rest spans the width, so anywhere on its band selects it — the same target the
// eye sees. Notes are tested first: where a note box overlaps a rest band, the note
// is what you meant.
// Hit-testing lives with the gestures now (core/roll-edit.js); the paint and gamaka
// paths still ask for it here.
const hitNote = (x,y) => rollEdit.hitNote(x,y);
const $ = id => document.getElementById(id);
let clipRel=null;   // copied curve, stored RELATIVE to its note's step (so it re-anchors on paste)
function enterDraw(i){ sel=i; mode='draw'; syncDelete();
  $('mode').textContent='draw the curve'; $('crumb').textContent='note '+(i+1)+' · '+NOTES[i].swara+NOTES[i].octave;
  for (const b of ['clear','copy','paste','back']) $(b).style.display='';   // draw-only buttons appear
  $('back').disabled=false; $('clear').disabled=!NOTES[i].curve; $('copy').disabled=!NOTES[i].curve; $('paste').disabled=!clipRel;
  setPlayBtn('▶','Play note'); $('rangectl').style.display=''; $('snapctl').style.display=''; $('tzoom').style.display='none'; resizeCanvas(); }
// Leaving the editor keeps the note SELECTED — you were just looking at it, and
// dropping the selection here would put delete back out of reach the moment you
// stepped out of an editor you only opened to look.
$('back').onclick=()=>{ mode='roll'; syncDelete(); $('mode').textContent='select a note'; $('crumb').textContent='';
  for (const b of ['clear','copy','paste','back']) $(b).style.display='none';   // draw-only buttons hidden in roll mode
  $('read').textContent=''; setPlayBtn('▶',playLabel());
  $('rangectl').style.display='none'; $('snapctl').style.display='none'; $('tzoom').style.display=''; resizeCanvas(); };
$('clear').onclick=()=>{ if (sel>=0 && NOTES[sel].curve){ pushUndo(); NOTES[sel].curve=null; $('clear').disabled=true; $('copy').disabled=true; render(); scheduleShare(); } };
function flashBtn(id,msg){ const b=$(id),t=b.textContent; b.textContent=msg; setTimeout(()=>b.textContent=t,1100); }
// Copy stores the curve relative to its note's step; Paste re-anchors it (transpose
// only — preserves the copied shape/tuning exactly), plays the target for feedback.
function copyFrom(i){ if (!NOTES[i].curve) return; const s0=NOTES[i].step; clipRel=NOTES[i].curve.map(([u,s])=>[u, s-s0]); $('paste').disabled=false; }
function pasteTo(i){ if (!clipRel) return; const s0=NOTES[i].step; NOTES[i].curve=clipRel.map(([u,d])=>[u, s0+d]);
  if (sel===i){ $('clear').disabled=false; $('copy').disabled=false; } render(); scheduleShare(); playNote(i); }
$('copy').onclick=()=>{ if (sel>=0&&NOTES[sel].curve){ copyFrom(sel); flashBtn('copy','Copied'); } };
$('paste').onclick=()=>{ if (sel>=0) pasteTo(sel); };
// desktop: right-click / ctrl-click a note in the roll to copy or paste its gamaka
let ctxNote=-1;
// Play button shows only an icon (compact on mobile); the words go in its title.
function setPlayBtn(icon, title){ const b=$('play'); b.textContent=icon; b.title=title; }
function setPlayIdle(){ if (!playing&&!paused) setPlayBtn('▶', playLabel()); }
cv.addEventListener('contextmenu', e=>{ if (mode!=='roll') return; e.preventDefault(); const {x,y}=evtPos(e);
  ctxNote=hitNote(x,y); ctxTime=Math.max(0,Math.min(TOTAL,tAtY(y))); const cm=$('ctxmenu');
  cm.querySelector('[data-act=copy]').disabled=!(ctxNote>=0&&NOTES[ctxNote].curve);
  cm.querySelector('[data-act=paste]').disabled=!(ctxNote>=0&&clipRel);
  cm.querySelector('[data-act=clearmk]').disabled=(markerA<=0.01&&markerB>=TOTAL-0.01);
  cm.style.left=Math.min(e.clientX, window.innerWidth-170)+'px'; cm.style.top=Math.min(e.clientY, window.innerHeight-210)+'px'; cm.style.display='block'; });
function hideCtx(){ $('ctxmenu').style.display='none'; }
$('ctxmenu').addEventListener('click', e=>{ const act=e.target.getAttribute&&e.target.getAttribute('data-act'); if (!act){ hideCtx(); return; }
  if (act==='copy'&&ctxNote>=0) copyFrom(ctxNote);
  else if (act==='paste'&&ctxNote>=0) pasteTo(ctxNote);
  else if (act==='seta'){ markerA=ctxTime; setPlayIdle(); render(); }
  else if (act==='setb'){ markerB=ctxTime; setPlayIdle(); render(); }
  else if (act==='clearmk'){ markerA=0; markerB=TOTAL; setPlayIdle(); render(); }
  else if (act==='playfrom'){ playFrom(ctxTime, (markerB!=null&&markerB>ctxTime)?markerB:TOTAL); }
  hideCtx(); });
// Draggable A/B gutter handles — grab and slide to set the play segment bounds.
function startMk(which){ return e=>{ e.preventDefault(); e.stopPropagation(); markerDrag=which; try{ $('mk'+which).setPointerCapture(e.pointerId); }catch(_){} }; }
$('mkA').addEventListener('pointerdown', startMk('A'));
$('mkB').addEventListener('pointerdown', startMk('B'));
window.addEventListener('pointermove', e=>{ if (!markerDrag) return; const r=cv.getBoundingClientRect();
  const t=Math.max(0,Math.min(TOTAL, tAtY(e.clientY-r.top))); if (markerDrag==='A') markerA=t; else markerB=t; setPlayIdle(); render(); });
window.addEventListener('pointerup', ()=>{ markerDrag=null; });
document.addEventListener('pointerdown', e=>{ if (!$('ctxmenu').contains(e.target)) hideCtx(); });
document.addEventListener('keydown', e=>{ if (e.key==='Escape') hideCtx(); });
// Windowed roll: redraw the visible slice, and record where the user put it. Only in
// roll mode — the curve editor's own collapse to scrollTop 0 must not be mistaken for
// someone scrolling to the top.
$('holder').addEventListener('scroll', ()=>{ hideCtx(); if (mode==='roll'){ rememberView(); render(); } });
// help popup
$('helpbtn').onclick=()=>{ const h=$('helppop'); h.hidden=!h.hidden; };
$('helpclose').onclick=()=>{ $('helppop').hidden=true; };
document.addEventListener('pointerdown', e=>{ const h=$('helppop'); if (!h.hidden && !h.contains(e.target) && e.target.id!=='helpbtn') h.hidden=true; });
document.addEventListener('keydown', e=>{ if (e.key==='Escape') $('helppop').hidden=true; });
$('rmin').onclick=()=>{ drawSpan=Math.max(10,drawSpan-8); resizeCanvas(); };
$('rplus').onclick=()=>{ drawSpan=Math.min(60,drawSpan+8); resizeCanvas(); };   // 60 ≈ a bit over an octave (53-EDO) each side
// Expand: scale up the roll (taller cells). Windowing means any zoom is safe — the
// canvas stays viewport-sized; only the scroll range grows. 1 = fully expanded floor.
$('tmin').onclick=()=>{ zoom=Math.max(1, Math.round((zoom-0.5)*10)/10); resizeCanvas(); };
$('tplus').onclick=()=>{ zoom=Math.min(8, Math.round((zoom+0.5)*10)/10); resizeCanvas(); };
// `+ note` toggle: paint mode is mutually exclusive with the roll's long-press grab
// (both handlers guard on paintMode, see the pointerdown listeners above), and with
// `✎ gamaka` mode below.
$('paintbtn').onclick=()=>{ paintMode=!paintMode; if (paintMode){ gamakaMode=false; $('gamakabtn').classList.remove('on'); }
  $('paintbtn').classList.toggle('on',paintMode); cv.style.cursor=paintMode?'crosshair':''; render(); };
// `✎ gamaka` toggle: shows draggable anchor dots on the roll (rendered in render()) and
// is mutually exclusive with `+ note` paint mode. Pointer handlers land in later tasks.
$('gamakabtn').onclick=()=>{ gamakaMode=!gamakaMode; if (gamakaMode){ paintMode=false; $('paintbtn').classList.remove('on'); }
  $('gamakabtn').classList.toggle('on',gamakaMode); $('snapctl').style.display=gamakaMode?'':'none'; cv.style.cursor=gamakaMode?'crosshair':''; render(); };
// Gamaka-on-move default: 'preserve pitch' (leave the abs curve — serialize emits shifted
// relative deltas) or 'move with note' (shift the abs curve so the deltas stay verbatim
// and the curve rides the note). Persisted; the post-move toast always offers the other.
const GKEY='ragamroll.gamakaOnMove';
let gamakaOnMove=localStorage.getItem(GKEY)||'preserve-pitch';
$('gmovesel').value=gamakaOnMove;
$('gmovesel').onchange=e=>{ gamakaOnMove=e.target.value; try{ localStorage.setItem(GKEY,gamakaOnMove); }catch(_){}; };
// Non-blocking toast: ~4s auto-dismiss, optional one-tap action.
let toastTimer=0;
function showToast(msg, actionLabel, onAction){ const t=$('toast'); t.innerHTML='';
  t.append(document.createTextNode(msg));
  if (actionLabel){ const b=document.createElement('button'); b.textContent=actionLabel;
    b.onclick=()=>{ hideToast(); onAction(); }; t.append(b); }
  t.style.display='flex'; clearTimeout(toastTimer); toastTimer=setTimeout(hideToast,4000); }
function hideToast(){ $('toast').style.display='none'; }
// Drone/tala levels are LIVE: each routes through a per-session gain bus, so a
// slider change scales the currently-playing drone / accent strums immediately.
$('dronevol').oninput=e=>{ droneVol=Number(e.target.value); if (audio) audio.setMix({ drone:droneVol }); };
$('talavol').oninput=e=>{ talaVol=Number(e.target.value); if (audio) audio.setMix({ tala:talaVol }); };
// Footer build/version — mirrors the app's Footer component (build-app-v0.sh stamps both).
$('footbuild').innerHTML=(BUILD_DATE?`built ${BUILD_DATE} · `:'')+`<span class="ver">${VERSION}</span>`;

// Sa reference pitch (playback transpose) — Auto = the composition's Sa (saRef).
// Changing it retunes saFreq only; the roll layout (steps) is anchored to saRef.
(function fillSa(){ let opts='<option value="">Auto</option>'; for (let m=40;m<=72;m++) opts+=`<option value="${m}">${midiToName(m)}</option>`; $('sapick').innerHTML=opts; })();
$('sapick').onchange=e=>{ saPlay=e.target.value===''?null:Number(e.target.value); saFreq=midiToFreq(saPlay==null?saRef:saPlay); render(); };
// Tempo slider — a multiplier of the composition tempo; affects playback speed only
// (the roll layout is in length-units, independent of tempo).
$('tempo').oninput=e=>{ tempoBpm=Math.round(compTempo*Number(e.target.value)); $('tempolbl').textContent=tempoBpm+' BPM'; };
// Sync the Sa / tempo controls to the current model (after a load/reload).
function syncControls(){ $('sapick').value=saPlay==null?'':String(saPlay);
  const auto=$('sapick').querySelector('option[value=""]'); if (auto) auto.textContent='Auto ('+midiToName(saRef)+')';
  $('tempo').value=String(Math.max(0.5,Math.min(2, tempoBpm/compTempo))); $('tempolbl').textContent=tempoBpm+' BPM';
  $('rt').textContent = curRaga ? `${curRaga} · ${curTala}` : '';
  // Raga/tala pickers apply only to a BLANK piece (no notes) — lock once notes exist.
  const blank = NOTES.length===0;
  $('ragasearch').disabled=!blank; $('talasel').disabled=!blank;
  $('editnote').textContent = blank ? 'pick a raga / tala, then type swaras below' : 'raga · tala locked while notes exist';
  $('ragasearch').value = curRaga || ''; $('talasel').value = curTalaName; }
// Set the Raga=/Tala= directive in the srgm (blank pieces only) and reload.
// A Raga pick seeds the piece with that raga's notation (curated draft, else a
// plain scale); a Tala pick only rewrites the directive (unchanged behaviour).
async function applyRagaTala(kind, name){ if (NOTES.length || !name) return;
  if (kind==='Raga'){
    // #ragasearch is free-text; canonicalize once so a non-canonical typed
    // case (e.g. "Mohanam") still hits drafts[name]/getRagaExt/getRagas().
    const cname = resolveRagaName(name) || name;
    const drafts = await loadDrafts();
    if (NOTES.length) return; // piece may no longer be blank after the async fetch
    const picked = chooseSeed(cname, drafts, getRagaExt(cname), getRagas());
    // seed the piece with the raga's notation, else fall back to a bare blank with Raga= set
    const seed = picked ? picked.srgm : `Raga=${cname},0\nTala=adi,4\nO=5 L=1\n`;
    loadSrc(seed, docName); setEditorH(editorH>10?editorH:Math.round((window.innerHeight||600)*0.35)); return;
  }
  // Tala (blank only): rewrite the Tala= directive and reload (unchanged behaviour)
  let s=srcText; const nv='Tala='+name+',4'; const re=/(^|\s)Tala=\S+/;
  s = re.test(s) ? s.replace(re, (m,p)=>p+nv) : nv+'\n'+s;
  loadSrc(s, docName); setEditorH(editorH>10?editorH:Math.round((window.innerHeight||600)*0.35));
}
// Back to the app: carry the composition CURRENTLY open here into the app (it reads
// the same localStorage key), so the app opens the same piece — not whatever it held.
$('backapp').onclick=e=>{ e.preventDefault(); try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}; location.href='./index.html'; };
// srgm editor: a slide-up panel below the buttons. Drag the grip to resize; tap to
// toggle. Native ctrl-z works for typing; edits reparse (debounced) → rebuild roll.
let editorH=0, gripDrag=null;
function setEditorH(h){ editorH=Math.max(0, Math.min(h, Math.round((window.innerHeight||600)*0.6)));
  $('editpanel').style.height=editorH+'px';
  if (editorH>0 && document.activeElement!==$('editor')) $('editor').value=srcText;
  requestAnimationFrame(resizeCanvas); }
$('grip').addEventListener('pointerdown', e=>{ e.preventDefault(); try{ $('grip').setPointerCapture(e.pointerId); }catch(_){}; gripDrag={y:e.clientY,h:editorH,moved:false}; });
$('grip').addEventListener('pointermove', e=>{ if (!gripDrag) return; const dy=gripDrag.y-e.clientY; if (Math.abs(dy)>3) gripDrag.moved=true; setEditorH(gripDrag.h+dy); });
$('grip').addEventListener('pointerup', ()=>{ if (gripDrag&&!gripDrag.moved) setEditorH(editorH>10?0:Math.round((window.innerHeight||600)*0.35)); gripDrag=null; });
$('editor').addEventListener('input', ()=>{ clearTimeout(editTimer); editTimer=setTimeout(onEditorInput, 300); });
$('ragasearch').onchange=()=>applyRagaTala('Raga', $('ragasearch').value.trim());
$('talasel').onchange=()=>applyRagaTala('Tala', $('talasel').value);
// Fullscreen toggle — on mobile this hides the browser address bar.
$('fsbtn').onclick=()=>{ const d=document, el=d.documentElement;
  if (!d.fullscreenElement && !d.webkitFullscreenElement){ (el.requestFullscreen||el.webkitRequestFullscreen||(()=>{})).call(el); }
  else { (d.exitFullscreen||d.webkitExitFullscreen||(()=>{})).call(d); } };
document.addEventListener('fullscreenchange', ()=>setTimeout(fit,100));

// ---------- audio ----------
let AC=null, live=null;
let droneVol=0.5, talaVol=0.5;   // 0..1; live via the per-session dBus/tBus gains
function ensureAudio(){ if (!AC){ try{ AC=new (window.AudioContext||window.webkitAudioContext)(); }catch(e){ return null; } }
  if (AC.state==='suspended') AC.resume();
  if (!live){ const osc=AC.createOscillator(); osc.type='triangle'; osc.frequency.value=freqOf(0);
    const gain=AC.createGain(); gain.gain.value=0; osc.connect(gain); gain.connect(AC.destination); osc.start();
    const dgain=AC.createGain(); dgain.gain.value=0; dgain.connect(AC.destination);
    for (const s of [-EDO,0]){ const o=AC.createOscillator(); o.type='sine'; o.frequency.value=freqOf(s); o.connect(dgain); o.start(); }
    live={osc,gain,dgain}; }
  return AC; }
function liveOn(){ ensureAudio(); if (!live) return; const now=AC.currentTime;
  live.gain.gain.cancelScheduledValues(now); live.gain.gain.setTargetAtTime(0.20,now,0.008); live.dgain.gain.setTargetAtTime(0.05,now,0.03); }
function liveSet(step){ if (live&&AC) live.osc.frequency.setTargetAtTime(freqOf(step),AC.currentTime,0.006); }
function liveOff(){ if (!live) return; const now=AC.currentTime; live.gain.gain.setTargetAtTime(0,now,0.03); live.dgain.gain.setTargetAtTime(0,now,0.05); }
// The voice, drone and strums live in core/roll-audio.js so the library page sounds
// a phrase exactly as the draw link it replaces does — same gamaka interpolation,
// same envelopes. draw keeps the transport: the audio module schedules and says when
// it starts, and the playhead below counts from there.
let audio=null;
function rollAudio(){ const a=ensureAudio(); if (!a) return null; if (!audio){ audio=createRollAudio(a, freqOf); audio.setMix({ drone:droneVol, tala:talaVol }); } return audio; }
function stopPlayback(){ playing=false; playPos=null; if (rafId){ cancelAnimationFrame(rafId); rafId=0; }
  if (audio) audio.stop();
  if (mode==='roll') render(); }
// playhead loop — advance a line down the roll and scroll so it stays in view ("rolls up")
function tick(){ if (!playing||!AC) return; const el=Math.max(0, AC.currentTime-playStart);
  const pos=playFromU + el/secPerUnit();
  if (pos>=playToU){ playing=false; playPos=null; setPlayBtn('▶',playLabel()); render(); return; }
  playPos=pos;
  // Auto-scroll so the playhead stays ~40% down the viewport (virtual coords). Setting
  // scrollTop fires the scroll listener → render(); we also render() to be safe.
  const hd=$('holder'); hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), (PAD.t+pos*pxU())-hd.clientHeight*0.4));
  render();
  rafId=requestAnimationFrame(tick); }
function playLabel(){ const lo=Math.min(markerA,markerB), hi=Math.max(markerA,markerB); return (lo>0.01||hi<TOTAL-0.01) ? 'Play A–B' : 'Play phrase'; }
function playNote(i){ const au=rollAudio(); if (!au) return; stopPlayback();
  au.note(NOTES[i], Math.max(0.5, NOTES[i].dur*secPerUnit())); }
function autoPlay(){ if (sel>=0&&NOTES[sel].curve) playNote(sel); }
// play the roll from `from` to `to` length-units (partial notes at the ends sound their portion)
function playFrom(from,to){ const au=rollAudio(); if (!au) return; from=Math.max(0,from); to=Math.min(TOTAL,to); if (to<=from) return;
  stopPlayback();
  const start=au.phrase({ notes:NOTES, starts, from, to, secPerUnit:secPerUnit(),
    tala:{ measure:talaMeasure, accents:talaAccents } });
  playing=true; paused=false; playStart=start; playFromU=from; playToU=to; playPos=from;
  setPlayBtn('⏸','Pause'); if (rafId) cancelAnimationFrame(rafId); rafId=requestAnimationFrame(tick); }
function pausePlayback(){ if (!playing) return; pausedAt=playPos; pausedTo=playToU; stopPlayback(); paused=true; playPos=pausedAt; setPlayBtn('▶','Resume'); render(); }
function segRange(){ return [Math.min(markerA,markerB), Math.max(markerA,markerB)]; }
$('play').onclick=()=>{ if (mode==='draw'){ playNote(sel); return; }
  if (playing){ pausePlayback(); return; }
  if (paused){ playFrom(pausedAt,pausedTo); return; }
  const [lo,hi]=segRange(); playFrom(lo,hi); };
$('stop').onclick=()=>{ stopPlayback(); paused=false; playPos=null; setPlayBtn('▶',playLabel()); if (mode==='roll') render(); };
// Back to the start of what Play would play -- marker A when a segment is set, the
// top of the piece otherwise. Distinct from Stop, which ends playback and takes the
// playhead off the roll entirely: rewinding PARKS the playhead at the start, so you
// can see where the next Play begins.
//
// It has to clear `paused`. Pause remembers where it stopped and Play resumes there,
// so rewinding a paused piece without clearing it would move the playhead to the top
// and then resume from the middle anyway -- the one bug this button invites.
$('rewind').onclick=()=>{ const [lo,hi]=segRange();
  if (playing){ stopPlayback(); playFrom(lo,hi); return; }   // restart from the top, still playing
  paused=false; pausedAt=lo; pausedTo=hi; playPos=lo;
  setPlayBtn('▶',playLabel()); if (mode==='roll') render(); };

// ---------- source text (inline gamaka) + share ----------
let shareLink='', shareTimer=null;
// The composition text with the drawn curves inline, each NOTE-RELATIVE (delta).
function inlineSrc(){ const curves={};
  // 2dp on the delta as well as on u -- rounding it to a whole step here would
  // undo the precision detect.js keeps, every time draw re-serialised.
  NOTES.forEach((n)=>{ if (n.curve) curves[n.tok]=n.curve.map(([u,s])=>[Math.round(u*100)/100, Math.round((s-n.step)*100)/100]); });
  return serializeInline(srcText, curves); }

// ---------- model<->srgm edit glue (note-edit core wiring) ----------
// Raga context for step<->swara naming, from the current composition's raga.
function ragaCtx(){ const { ragaSteps, ragaSwaraName } = buildRagaSteps(curRaga || ''); return { useRaga: !!(curRaga && ragaSteps), ragaSteps, ragaSwaraName }; }
// Snapshot of the current model keyed by source-token ordinal (rests excluded).
function modelByTok(){ const m=new Map(); NOTES.forEach(n=>m.set(n.tok,{ step:n.step, dur:n.dur, octave:n.octave, curve:n.curve })); return m; }
// The raga's pitch-classes (single-octave 53-EDO MOD-steps) for pitch snapping.
// IMPORTANT: snapToRagaRow(step, gridSteps) reconstructs the octave from `step`
// itself, so gridSteps must be single-octave mods (0..52), NOT absolute multi-octave
// rows — passing absolute rows would double-count the octave. Raga mode => the
// raga's mod-steps; no-raga (c12) => the distinct pitch-classes of existing notes.
function ragaRowSteps(){ const { ragaSteps }=ragaCtx();
  if (ragaSteps) return [...ragaSteps];
  return [...new Set(NOTES.map(n=>((n.step%EDO)+EDO)%EDO))].sort((a,b)=>a-b); }

// ---- undo (structural edits round-trip through srcText) ----
let undoStack=[];
function pushUndo(){ undoStack.push(srcText); if (undoStack.length>50) undoStack.shift(); }
async function undo(){ hideToast(); if (!undoStack.length) return; const prev=undoStack.pop();
  if (mode==='draw') $('back').click(); buildModel(prev); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
$('undobtn').onclick=()=>{ undo(); };
// Ctrl/Cmd+Z triggers structural undo only in roll mode and only outside the srgm
// editor textarea, so native textarea undo (typing) still works while editing text.
document.addEventListener('keydown', e=>{ if ((e.ctrlKey||e.metaKey) && !e.shiftKey && (e.key==='z'||e.key==='Z') && mode==='roll' && document.activeElement!==$('editor')){ e.preventDefault(); undo(); } });
$('delbtn').onclick=()=>{ deleteSelected(); };
// Del/Backspace, but never while the srgm editor has focus — there the key belongs
// to the text, and deleting a note out from under someone who is typing is the kind
// of thing there is no obvious way back from.
document.addEventListener('keydown', e=>{
  if (e.key!=='Delete' && e.key!=='Backspace') return;
  if (document.activeElement===$('editor')) return;
  const t=document.activeElement; if (t && /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName)) return;
  if (!(selRest>=0 || (sel>=0 && NOTES[sel]))) return;
  e.preventDefault(); deleteSelected();
});

// Re-serialize the current model to srgm, then rebuild everything from that text.
// A rest's new length, written back to its own token.
// Delete whatever is selected — a note, or a rest. Removing a note leaves NO silence
// in its place: the piece gets shorter, which is what deleting a note means. Paint a
// rest if a gap is wanted.
async function deleteSelected(){
  const tok = selRest>=0 ? selRest : (sel>=0 && NOTES[sel] ? NOTES[sel].tok : -1);
  if (tok<0) return;
  pushUndo();
  const wasDrawing = mode==='draw';
  selRest=-1; sel=-1;
  // The note being curve-edited is gone, so there is nothing left to edit — go back
  // to the roll rather than leaving the editor pointed at a note that no longer is.
  if (wasDrawing) $('back').click();
  await commitEdit({ deletes:new Set([tok]), deriveOctave:true });
  syncDelete();
}
// The button is only live when something is selected — a delete with no target is
// not a no-op the user can see, it just looks broken.
function syncDelete(){ const b=$('delbtn'); if (!b) return;
  // Also in draw mode: clicking a note OPENS it for curve editing, so that is exactly
  // where someone looking at a note they want rid of will be.
  b.disabled = !(selRest>=0 || (sel>=0 && NOTES[sel]));
}
// What an edit COSTS is draw's own business — re-parsing into these globals, redrawing,
// rebuilding the share link. What it MEANS for the notation is not: applyEdit is shared
// with the app, which does the same serialise-and-tidy and then hands the string to a
// worker instead.
async function commitEdit({ changed=new Set(), inserts=new Map(), deletes=new Set(), deriveOctave=false, restDurs=undefined }){
  const newSrc=applyEdit(srcText, { model:modelByTok(), changed, inserts, deletes, deriveOctave, ctx:ragaCtx(), restDurs });
  buildModel(newSrc); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
// Reflect srcText into the editor textarea — but never clobber the box the user
// is actively typing in (that also preserves its native ctrl-z history).
function syncEditor(){ const t=$('editor'); if (t && document.activeElement!==t) t.value=srcText; }
// A draw changed the curves: regenerate the inline srgm, show it in the editor,
// persist it, and refresh the share link.
// ROUND TRIP: inlineSrc() REWRITES the source to carry the edited curves, and it
// is what gets saved, shared and reloaded. If it emits something the parser
// cannot read back, whatever it mangled is already lost -- so it is read back
// here, where it was written, rather than by whoever opens the link.
// What a share link carries: the notation, plus the mixer levels ONLY when they
// are not the defaults. Otherwise every ordinary link would change shape for a
// setting nobody touched. Both places that build a link go through here — a link
// opened with the tala silenced must not lose that on the first edit, and editing
// is exactly what the other builder runs on.
const shareBody = (src) => (droneVol!==DEFAULT_MIX.dv || talaVol!==DEFAULT_MIX.tv)
  ? JSON.stringify({ v:2, srgm:src, mix:{ dv:droneVol, tv:talaVol } })
  : src;
async function rebuildShare(){ srcText=inlineSrc(); syncEditor();
  try { reportDiagnostics(parse(srcText), true); }
  catch(_){ reportDiagnostics({ diagnostics:[{ message:'the generated notation could not be parsed at all' }] }, true); }
  try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}
  try{ shareLink=location.origin+location.pathname+'#'+await encodeShareToken(shareBody(srcText)); }catch(e){ shareLink=''; } }
function scheduleShare(){ clearTimeout(shareTimer); shareTimer=setTimeout(rebuildShare,150); }
// Editor edits: reparse the srgm the user typed (debounced), rebuild the roll.
let editTimer=null;
async function onEditorInput(){ hideToast(); if (mode==='draw') $('back').click();   // a reparse changes NOTES; leave draw mode so sel can't dangle
  srcText=$('editor').value; buildModel(srcText);
  syncControls(); resizeCanvas(); render();
  try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}
  try{ shareLink=location.origin+location.pathname+'#'+await encodeShareToken(shareBody(srcText)); }catch(e){ shareLink=''; } }
$('share').onclick=()=>{ const url=shareLink; if (!url){ rebuildShare(); return; }
  const b=$('share'), orig=b.textContent, done=m=>{ b.textContent=m; setTimeout(()=>b.textContent=orig,1800); };
  if (navigator.share){ navigator.share({ title:'RagamRoll gamakas', url }).then(()=>done('Shared ✓')).catch(()=>{}); return; }
  if (navigator.clipboard){ navigator.clipboard.writeText(url).then(()=>done('Copied ✓')).catch(()=>window.prompt('Copy this link:',url)); return; }
  window.prompt('Copy this link:', url); };

// ---------- load / boot ----------
// Debug dump: log the note map (index, source token ordinal, swara, curve points).
function logNotes(tag){ try{ console.log(`[draw] ${tag} — idx:tok swara [pts]:`,
  NOTES.map((n,i)=>`${i}:t${n.tok} ${n.swara}${n.octave}${n.curve?` [${n.curve.length}]`:''}`).join('   ')); }catch(_){}
}
// The mixer levels a link can carry. Kept to what a link should be allowed to set
// on someone else's page: how loud the accompaniment is, nothing about the piece.
// Absent keys keep the page's current value, so a link may set one and leave the
// other alone.
const DEFAULT_MIX={ dv:0.5, tv:0.5 };
function applyMix(u){
  if (!u || typeof u!=='object') return;
  const set=(k,v)=>{ if (!(typeof v==='number') || !isFinite(v)) return; const c=Math.max(0,Math.min(1,v));
    if (k==='dv'){ droneVol=c; if ($('dronevol')) $('dronevol').value=String(c); if (audio) audio.setMix({ drone:c }); }
    else { talaVol=c; if ($('talavol')) $('talavol').value=String(c); if (audio) audio.setMix({ tala:c }); } };
  set('dv',u.dv); set('tv',u.tv);
}
// A share hash is pako(srgm text), or pako(JSON {v:2, srgm, mix}) when the link
// carries mixer levels — the /ragas links do, to open with the tala strums at zero:
// those recordings are free-rhythm arohana/avarohana and signature phrases, so
// veena accents on a cycle nobody sang are noise. Legacy links were
// pako(JSON {v,src,g}); detect and convert those once (apply the index-keyed
// curves; they re-emit inline).
function applyShared(decoded){
  hideToast();
  userGridMin = userGridMax = userGridBottom = null;   // new composition: start at auto/seed bounds, not a stale stretch
  viewT = null;                                        // ...and at its beginning, not wherever the LAST piece was being read
  let legacy=null, carried=null;
  try{ const o=JSON.parse(decoded);
    if (o&&typeof o.src==='string') legacy=o;
    else if (o&&typeof o.srgm==='string') carried=o; }catch(_){}
  console.log(`[draw] pako decoded — ${legacy?'LEGACY {v,src,g}':carried?'{v:2, srgm, mix}':'raw srgm text'} (${decoded.length} chars):\n%s`,
    legacy||carried ? JSON.stringify(legacy||carried, null, 1) : decoded);
  if (legacy){ buildModel(legacy.src);
    if (legacy.g) for (const k in legacy.g){ const i=+k; if (NOTES[i]) NOTES[i].curve=legacy.g[k].map(p=>[p[0],p[1]]); } }
  else if (carried){ applyMix(carried.mix); buildModel(carried.srgm); }
  else buildModel(decoded);   // raw srgm text; inline gamaka decoded in buildModel
  logNotes('after applyShared');
}
async function loadComposition(){
  const h=location.hash.replace(/^#/,'');
  if (h){ try{ applyShared(await decodeShareToken(h)); return; }catch(e){ console.warn('[draw] pako decode failed', e); } }
  const ls=localStorage.getItem(LS_KEY) || 'Raga=hamsadhwani,0 O=5 L=1 S R G P N >S';
  console.log(`[draw] loaded from localStorage (${ls.length} chars):\n%s`, ls);
  buildModel(ls); logNotes('after localStorage load');
}
// ---------- composition I/O: Open (examples / file / link), Save, Export MIDI ----------
const baseName = s => String(s||'ragamroll').replace(/^.*[\/\\]/,'').replace(/\.[^.]+$/,'') || 'ragamroll';
// Load a whole new composition into the roll + editor (and persist / reshare).
async function loadSrc(text, name){ hideToast(); if (mode==='draw') $('back').click(); stopPlayback();
  userGridMin = userGridMax = userGridBottom = null;   // new composition: start at auto/seed bounds, not a stale stretch
  viewT = null;                                        // ...and at its beginning, not wherever the LAST piece was being read
  if (name) docName=name; buildModel(text); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
async function pasteLink(){ const inp=window.prompt('Paste a RagamRoll share link or pako token:'); if (!inp) return;
  const m=/pako:[A-Za-z0-9\-_]+/.exec(inp); const tok=m?m[0]:inp.trim().replace(/^#/,'');
  try{ if (mode==='draw') $('back').click(); stopPlayback(); applyShared(await decodeShareToken(tok));
    syncControls(); resizeCanvas(); render(); await rebuildShare(); }
  catch(e){ window.alert('That isn’t a valid RagamRoll link — it should contain a pako: token.'); } }
// Open ▾ menu (examples list + open file + paste link)
function hideOpen(){ $('openmenu').style.display='none'; }
$('openbtn').onclick=e=>{ e.stopPropagation(); const m=$('openmenu');
  if (m.style.display==='block'){ hideOpen(); return; }
  m.style.display='block'; const r=$('openbtn').getBoundingClientRect();
  m.style.left=Math.max(6, Math.min(r.left, innerWidth-m.offsetWidth-8))+'px';
  m.style.top=Math.max(6, r.top-m.offsetHeight-6)+'px'; };
document.addEventListener('pointerdown', e=>{ const m=$('openmenu'); if (m.style.display==='block' && !m.contains(e.target) && e.target!==$('openbtn')) hideOpen(); });
$('exsel').onchange=async e=>{ const name=e.target.value; e.target.value=''; if (!name) return; hideOpen();
  try{ loadSrc(await fetch('./examples/'+name+'.srgm').then(r=>{ if(!r.ok) throw 0; return r.text(); }), name); }
  catch(_){ window.alert('Could not load that example.'); } };
$('openmenu').addEventListener('click', e=>{ const act=e.target.getAttribute('data-act'); if (!act) return; hideOpen();
  if (act==='new'){ loadSrc(blankSrc(), 'untitled'); setEditorH(Math.round((window.innerHeight||600)*0.35)); }
  else if (act==='file') $('fileinput').click(); else if (act==='link') pasteLink(); });
$('fileinput').onchange=async e=>{ const f=e.target.files[0]; e.target.value=''; if (f) loadSrc(await f.text(), baseName(f.name)); };
// Save / Export MIDI (gamakas are audio-only; MIDI stays plain)
function download(name, data, type){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([data],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
$('save').onclick=()=>download(docName+'.srgm', srcText, 'text/plain');
$('exportmidi').onclick=()=>{ try{ download(docName+'.mid', writeSMF(buildSequence(parse(srcText))), 'audio/midi'); }catch(e){ window.alert('MIDI export failed: '+e.message); } };
window.__rr = { roll:()=>roll,   // the roll instance, so a guard can ask it what it worked out — same shape as the app's __app.roll()
  notes:()=>NOTES, rests:()=>RESTS.map(r=>({...r})), get selRest(){ return selRest; },
  intents:()=>INTENT_LOG.map(i=>({...i})), clearIntents:()=>{ INTENT_LOG.length=0; }, get mode(){ return mode; }, get gamakaMode(){ return gamakaMode; },
  get delEnabled(){ return !$('delbtn').disabled; }, restEdgeY:(tok)=>{ const r=RESTS.find(x=>x.tok===tok); return r?Y(r.t0+r.dur):null; },
  yRange:()=>geo().yRange, restMidY:(tok)=>{ const r=RESTS.find(x=>x.tok===tok); return r?Y(r.t0+r.dur/2):null; }, X, Y, starts:()=>starts, get playing(){ return playing; }, get paused(){ return paused; }, get stepMin(){ return stepMin; }, get stepMax(){ return stepMax; }, get padTop(){ return PAD.t; }, gridSteps:()=>gridPitches.map(g=>g.step), labelChipW:()=>14, get shareLink(){ return shareLink; }, get playPos(){ return playPos; }, get markerA(){ return markerA; }, get markerB(){ return markerB; }, get talaMeasure(){ return talaMeasure; }, get talaAccents(){ return talaAccents; }, get droneVol(){ return droneVol; }, get talaVol(){ return talaVol; }, inlineSrc:()=>inlineSrc(), rebuild:()=>rebuildShare(), get src(){ return srcText; } };
// Populate the examples dropdown from the manifest (same source as the app).
fetch('./examples/index.json').then(r=>r.json()).then(list=>{
  const sel=$('exsel'); for (const n of list){ const o=document.createElement('option'); o.value=n; o.textContent=n; sel.appendChild(o); }
}).catch(()=>{});
Promise.all([
  fetch('./core/raga-db.json').then(r=>r.json()),   // one database: scale + mela + shrutis + arohana, aliases folded in
]).then(([db])=>{ const ragas=db; setRagas(db); setRagaExt(db);
    const ragaNames=Object.keys(ragas).filter(n=>!/^mela_\d+$/i.test(n)).sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase())); defaultRaga=ragaNames[0]||'c12';
    const rl=$('ragalist'); for (const n of ragaNames){ const o=document.createElement('option'); o.value=n; rl.appendChild(o); }
    const ts=$('talasel'); for (const n of Object.keys(TALA_MAP)){ const o=document.createElement('option'); o.value=n; o.textContent=n; ts.appendChild(o); }
    return loadComposition(); })
  .then(()=>{ window.addEventListener('resize',fit); if (window.visualViewport) window.visualViewport.addEventListener('resize',fit);
    window.addEventListener('orientationchange',()=>setTimeout(fit,200));
    new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
    if (!NOTES.length) $('mode').textContent='no notes — open a composition in the app first';
    syncControls(); fit(); resizeCanvas(); rebuildShare(); });
