// Gamaka draw page. Opens the current composition (localStorage, or a shared
// #pako link) as a pitch/time roll and lets the user draw a pitch curve per note.
// Pitch is 53-EDO (22-shruti): notes sit on their default shruti, snap targets
// the 22 shrutis, audio is microtonal. Curves + the srgm source pack into a
// #pako link (melody + gamakas).
import { parse, TALA_MAP } from './core/parser.js';
import { setRagas, getRagas, resolveRagaName } from './core/raga-base.js';
import { setRagaExt, getRagaExt } from './core/raga-ext.js';
import { chooseSeed } from './core/raga-seed.js';
import { midiToFreq } from './audio/schedule.js';
import { BOXES, EDO, stepFreq } from './core/shruti.js';
import { encodeShareToken, decodeShareToken } from './core/share.js';
import { VERSION, BUILD_DATE } from './version.js';
import { midiToName } from './core/tuning.js';
import { serializeInline, sampleCurve } from './core/gamaka-inline.js';
import { buildRollModel } from './core/roll-model.js';
import { createRagamRoll } from './core/ragamroll.js';
import { createRollAudio } from './core/roll-audio.js';
import { createRollEdit } from './core/roll-edit.js';
import { anchorsOf, resplitAt } from './core/note-split.js';
import { extractAnchors, pointsToAnchors, addAnchor, removeAnchor, moveAnchor } from './core/gamaka-curve.js';
import { buildSequence } from './core/midi/sequence.js';
import { writeSMF } from './core/midi/smf.js';
import { serializeModel, snapToRagaRow, snapToAkshara, placePaint, splitSpans, octMarks } from './core/note-edit.js';
import { buildRagaSteps } from './core/detect-raga-helper.js';
// Aliased: shruti.js exports a DIFFERENT stepForLetter(scale, letter). This one
// is (letter, approxStep, ragaSwaraName) -> the raga's own step for that letter.
import { stepToSwara } from './core/detect.js';

const LS_KEY = 'ragamroll.srgm';
const SHRUTI = [...new Set(BOXES.map(b => b.step))].sort((a, b) => a - b);   // 22 steps in an octave

// ---------- model built from the parsed composition ----------
let NOTES = [];        // [{step, dur, swara, octave, curve:null|[[u,step]...]}]
let saRef = 60, saFreq = midiToFreq(60), tempoBpm = 120, TOTAL = 0;
let saPlay = null;     // Sa reference-pitch override (midi); null = auto (= saRef, the layout anchor)
let compTempo = 120;   // the composition's own tempo; the tempo slider is a multiplier of this
let starts = [], RESTS = [], selRest = -1, gridPitches = [], stepMin = -26, stepMax = 66, srcText = '';
let contentEnd = 0;   // true content end from buildModel's starts-loop cursor `t` (rests included; 0 for a blank piece)
let userGridMin = null, userGridMax = null, userGridBottom = null;  // handle-stretched roll bounds (view-state, NOT saved)
let talaMeasure = 0, talaAccents = [], talaBeat = 0;   // cycle length + 1-based accent slots + akshara length (length-units)
let docName = 'ragamroll';               // base filename for Save / Export MIDI
let curRaga = '', curTala = '', curTalaName = 'adi';   // readout + current tala name (for the picker)
let defaultRaga = 'c12';                                 // set at boot to the first raga in the picker list
const blankSrc = () => `Raga=${defaultRaga},0\nTala=adi,4\nO=5 L=1\n`;   // Blank/New skeleton (no notes)

// Everything the parser could not honour, shown where the piece is. The parser
// has always recorded these -- a dropped gamaka arrives as "malformed attributes
// ... playing the plain note" -- but only index.html ever displayed them, so in
// draw a corrupted gamaka silently became a plain note and the notation looked
// fine. Silence is the bug: the note still plays, just not as written.
function reportDiagnostics(model, generated){
  const el = document.getElementById('parsewarn');
  if (!el) return;
  const ds = (model && model.diagnostics) || [];
  if (!ds.length) { el.style.display = 'none'; el.innerHTML = ''; return; }
  el.innerHTML = '<button type="button">dismiss</button><b>' + (generated
    ? 'This notation was generated by RagaM-Roll and cannot be read back — that is a bug, please report it.'
    : ds.length + ' part(s) of this notation could not be read as written.') +
    '</b> What is playing instead:<ul>' +
    ds.map(d => `<li>${d.message.replace(/[<&]/g, c => ({'<':'&lt;','&':'&amp;'}[c]))}</li>`).join('') +
    '</ul>';
  el.querySelector('button').onclick = () => { el.style.display = 'none'; };
  el.style.display = '';
}

// Notation in, roll out. The derivation itself lives in core/roll-model.js so the
// library page and the app read a piece the same way draw does; what stays here is
// draw's own state around it — the tempo slider's baseline, the Sa override, the
// segment markers, the name the tala dialog shows.
function buildModel(src){
  srcText = src || '';
  const model = parse(srcText);
  reportDiagnostics(model);
  const m = buildRollModel(model);
  roll.setModel(m);
  NOTES = m.notes; starts = m.starts; RESTS = m.rests; contentEnd = m.contentEnd;
  if (!RESTS.some((r) => r.tok === selRest)) selRest = -1;   // the selected rest may not have survived the edit
  compTempo = m.tempo;
  tempoBpm = compTempo;   // reset to the composition tempo on (re)load; the slider re-applies its multiplier
  saRef = m.saRef;
  saPlay = null;          // reset Sa override to auto on a new composition
  saFreq = midiToFreq(saRef);   // saRef is the LAYOUT anchor (steps); saPlay only retunes playback
  curRaga = m.raga;
  talaMeasure = m.tala.measure; talaAccents = m.tala.accents; talaBeat = m.tala.beat;
  curTala = m.talaProps ? `beat ${m.talaProps.beat}` : '';
  curTalaName = (srcText.match(/(?:^|\s)Tala=([A-Za-z0-9]+)/) || [])[1] || 'adi';
  recomputeGridBounds();
  markerA = 0; markerB = TOTAL;   // segment bounds default to the whole piece; draggable in the gutter
}
// Recompute TOTAL/stepMin/stepMax/gridPitches from the current NOTES/starts/
// talaMeasure/curRaga/userGrid* module state. Pulled out of buildModel's tail so a
// live handle-stretch (userGrid* changed, nothing re-parsed) can re-derive the grid
// bounds without re-running the parser. Does NOT touch userGrid* itself — only
// loadSrc/applyShared reset those (new composition), same invariant as before.
function recomputeGridBounds(){
  roll.setUser({ min:userGridMin, max:userGridMax, bottom:userGridBottom });
  const b = roll.bounds();
  TOTAL = b.total; stepMin = b.stepMin; stepMax = b.stepMax; gridPitches = b.gridPitches;
}
const freqOf = step => stepFreq(saFreq, step);
const secPerUnit = () => 30 / tempoBpm;
function snapStep(s){ const oct = Math.floor(s / EDO), base = s - oct * EDO; let best = SHRUTI[0], bd = Infinity;
  for (const sh of [...SHRUTI, EDO]){ const d = Math.abs(base - sh); if (d < bd){ bd = d; best = sh; } }
  return oct * EDO + best; }

// ---------- canvas ----------
const cv = document.getElementById('cv');
let mode='roll', sel=-1, drawing=false, drawSpan=22, dragIdx=-1;
// Roll-mode long-press grab (move/resize a note). paintMode is wired to the
// `+ note` toolbar toggle below; grab and paint gestures are mutually exclusive.
let paintMode=false, gamakaMode=false;   // the press/drag gestures themselves live in core/roll-edit.js
let paint=null;   // paint={ts, step?, rest?, dur, pid} — in-progress paint-a-note/rest drag (roll mode, paintMode on)
let gamaStroke=null;   // in-roll gamaka gesture: {gi, pid, dragIdx, downX, downY, buffer, mode:'anchor'|'free'|'pending'}
const HANDLE_PX=18;
const REST_LANE_PX=22;   // width of the rest-paint gutter at the left edge of the plot area (roll, paint mode)
const ROLL_TOUCH_ACTION='pan-y';   // touchAction roll mode uses when idle (matches resizeCanvas below)
// Grid stretch-handles (pitch-low/pitch-high/time-bottom) — shared sizing between
// the render() draw and hitGridHandle()'s hit-test so they stay in lockstep.
const GRIP_THICK=14, GRIP_LEN=HANDLE_PX*2.6;
let handleDrag=null;   // {which:'pmin'|'pmax'|'tbottom', pid}
// TEMP DEBUG (grid-handle grab diagnosis) — remove after diagnosing.
let zoom = 1;   // expand multiplier the roll scales time by (1 = shortest note cell at its minimum readable height)
const yVirt = t => { syncView(); return roll.yVirt(t); };   // roll virtual y (content coords, pre-scroll) — the gutter handles sit at these
const pxU = () => { syncView(); return roll.pxPerUnit(); };   // pixels per length-unit
const virtH = () => { syncView(); return roll.virtH(); };     // full scroll height of the roll
let playing=false, paused=false, playStart=0, rafId=0, playPos=null;   // playhead (length-units)
let playFromU=0, playToU=0, pausedAt=0, pausedTo=0;                    // playback range + pause point
let markerA=0, markerB=0, ctxTime=0, markerDrag=null;                 // A–B segment markers (length-units) + drag state
const cssvar = k => getComputedStyle(document.documentElement).getPropertyValue(k).trim();
// The roll itself — canvas, sizing, the scroll window, the grid it derives. draw
// supplies the palette and its editing chrome and keeps everything else: the audio,
// the transport, the notation, and every gesture that changes a note.
const roll = createRagamRoll({ holder: document.getElementById('holder'), content: document.getElementById('content'), canvas: cv }, {
  touchAction: ROLL_TOUCH_ACTION,
  palette: () => ({ amber:cssvar('--amber'), amberS:cssvar('--amberSoft'), teal:cssvar('--teal'),
    terra:cssvar('--terra'), hair:cssvar('--hair2'), muted:cssvar('--muted'),
    panel2:cssvar('--panel2'), mono:cssvar('--mono') }),
  hooks: { underGrid: drawRestGutter, overNotes: drawEditChrome, top: drawHandles },
});
const ctx = roll.ctx, PAD = roll.pad;
// Hit-testing reads the coordinates the roll actually drew with, so a note cannot be
// visible in one place and grabbable in another.
function geo(){ syncView(); return roll.geometry(); }
const plot = () => geo().plot;
function X(s){ return geo().X(s); }
function stepAtX(px){ return geo().stepAtX(px); }
function yStartEnd(){ return geo().yRange; }
function Y(t){ return geo().Y(t); }
function tAtY(py){ return geo().tAtY(py); }

function fit(){ const h=(window.visualViewport&&window.visualViewport.height)||window.innerHeight;
  document.getElementById('wrap').style.height=h+'px'; requestAnimationFrame(resizeCanvas); }
function resizeCanvas(){ syncView(); roll.resize(); positionHandles(); }

// draw's state, pushed into the roll before anything reads or draws it. The roll is
// told what to show; it never reaches back for it.
function syncView(){
  roll.setView({ mode, sel, selRest, drawSpan, zoom, playPos, markerA, markerB,
    saMidi: saPlay==null ? saRef : saPlay, grabIdx: rollEdit ? rollEdit.grabbedIndex() : -1 });
}
// ---- editing chrome ----
// Painted through the roll's hooks, because it is interleaved with the roll's own
// layers rather than sitting on top: the rest gutter goes under the pitch lines, the
// gamaka anchors over the notes but under the segment markers. Each hook is handed
// the geometry, so the chrome and the roll cannot disagree about where anything is.
function drawRestGutter(g){ const p=g.plot, [sa,sb]=g.xRange, C=roll.ctx;
  // A faint band at the left edge, paint mode only — pressing inside it paints a rest
  // (a silent gap) instead of a note. Same REST_LANE_PX as the pointerdown check.
  if (mode==='roll' && paintMode){ C.fillStyle='rgba(216,161,63,.09)'; C.fillRect(p.x,p.y,REST_LANE_PX,p.h);
    C.strokeStyle=cssvar('--hair2'); C.lineWidth=1; C.beginPath(); C.moveTo(p.x+REST_LANE_PX,p.y); C.lineTo(p.x+REST_LANE_PX,p.y+p.h); C.stroke();
    C.fillStyle=cssvar('--muted'); C.globalAlpha=.8; C.textAlign='center'; C.font='bold 11px '+cssvar('--mono');
    C.fillText('z', p.x+REST_LANE_PX/2, p.y+13); C.globalAlpha=1; C.font='11px '+cssvar('--mono'); }
  // Draw mode zooms onto one note and shows every shruti — you are placing a pitch by
  // hand there, not reading a raga.
  if (mode==='draw'){ for (let oct=Math.floor(sa/EDO)-1; oct<=Math.floor(sb/EDO)+1; oct++) for (const sh of SHRUTI){ const s=oct*EDO+sh;
    if (s<sa||s>sb) continue; const x=g.X(s); C.strokeStyle=cssvar('--hair2'); C.globalAlpha=.5; C.beginPath(); C.moveTo(x,p.y); C.lineTo(x,p.y+p.h); C.stroke(); C.globalAlpha=1; } }
}
function drawEditChrome(g){ const p=g.plot, X=g.X, Y=g.Y, C=roll.ctx, teal=cssvar('--teal');
  if (mode==='roll' && gamakaMode) for (let i=0;i<NOTES.length;i++){ const c=NOTES[i].curve; if (!c) continue;
    const t0=starts[i], t1=t0+NOTES[i].dur;
    for (const [u,st] of c){ const cx=X(st), cy=Y(t0+(t1-t0)*u);
      C.fillStyle=teal; C.globalAlpha=.9; C.beginPath(); C.arc(cx,cy,4,0,6.283); C.fill(); C.globalAlpha=1;
      C.strokeStyle='rgba(0,0,0,.35)'; C.lineWidth=.7; C.stroke(); } }
  if (paint){ const y0=Y(paint.ts), y1=Y(paint.ts+paint.dur);
    if (paint.rest){ const xc=p.x+REST_LANE_PX/2;
      C.fillStyle='#999'; C.globalAlpha=0.4; roundRect(xc-8,y0,16,Math.max(4,y1-y0),4); C.fill(); C.globalAlpha=1; }
    else { const xc=X(paint.step);
      C.fillStyle='#9fc'; C.globalAlpha=0.35; roundRect(xc-8,y0,16,Math.max(4,y1-y0),4); C.fill(); C.globalAlpha=1; } }
  if (mode==='draw'&&!NOTES[sel].curve){ C.fillStyle=cssvar('--muted'); C.textAlign='center'; C.font='13px '+cssvar('--sans');
    C.fillText('drag top→bottom to draw the pitch', p.x+p.w/2, p.y+p.h/2); }
  if (mode==='draw'&&NOTES[sel].curve&&!drawing){ const c=NOTES[sel].curve,[t0,t1]=g.yRange;
    for (let k=0;k<c.length;k++){ const cx=X(c[k][1]),cy=Y(t0+(t1-t0)*c[k][0]);
      C.beginPath();C.arc(cx,cy,6.5,0,7);C.fillStyle=cssvar('--bg');C.fill();
      C.lineWidth=2;C.strokeStyle=teal;C.stroke(); C.beginPath();C.arc(cx,cy,2.4,0,7);C.fillStyle=teal;C.fill(); } }
}
function drawHandles(){ if (mode==='roll') drawGridHandles(cssvar('--teal')); }

function render(){ syncView(); roll.render(); positionHandles(); }
// Grip dots inside a handle tab, perpendicular to its drag axis (a row of dots
// along the axis you CAN'T drag hints "grab and slide the other way").
function gripDots(cx,cy,axis){ ctx.fillStyle='#08110d';
  for (let i=-1;i<=1;i++){ if (axis==='h') ctx.fillRect(cx-1, cy+i*4-1, 2, 2); else ctx.fillRect(cx+i*4-1, cy-1, 2, 2); } }
// The 3 grid stretch-handles: pitch-low/pitch-high (drag horizontally — resize the
// pitch axis) and time-bottom (drag vertically — resize the time axis; the top of
// the time axis stays pinned at t=0). Positions here MUST match hitGridHandle()'s
// hit-test math exactly (shared GRIP_THICK/GRIP_LEN constants).
function drawGridHandles(teal){ const p=plot();
  const drawTab=(cx,cy,w,h,axis)=>{ ctx.fillStyle=teal; ctx.globalAlpha=.85; roundRect(cx-w/2,cy-h/2,w,h,4); ctx.fill(); ctx.globalAlpha=1;
    ctx.strokeStyle='rgba(0,0,0,.3)'; ctx.lineWidth=.6; ctx.stroke(); gripDots(cx,cy,axis); };
  const yMid=p.y+p.h/2;
  // pitch-low: nudged a few px right of the plot edge so it clears the A/B gutter border.
  drawTab(Math.max(p.x+GRIP_THICK/2+3, X(stepMin)), yMid, GRIP_THICK, GRIP_LEN, 'h');
  // pitch-high.
  drawTab(X(stepMax), yMid, GRIP_THICK, GRIP_LEN, 'h');
  // time-bottom: a STICKY '+ time' button pinned to the bottom of the viewport (always
  // visible; click-to-extend — no scrolling to find it). Drawn last so it sits on top.
  const yBot=roll.size().h-GRIP_THICK/2-6;
  drawTab(p.x+p.w/2, yBot, GRIP_LEN, GRIP_THICK, 'v');
  ctx.fillStyle='#031'; ctx.font='bold 12px '+cssvar('--mono'); ctx.textAlign='center'; ctx.textBaseline='middle';
  ctx.fillText('+ time', p.x+p.w/2, yBot); ctx.textBaseline='alphabetic'; ctx.font='11px '+cssvar('--mono');
}
// Hit-test the 3 grid handles (roll mode only); returns 'pmin'|'pmax'|'tbottom'|null.
// Mirrors drawGridHandles()'s positions with a generous (HANDLE_PX) touch radius.
function hitGridHandle(x,y){ if (mode!=='roll') return null; const p=plot();
  const yMid=p.y+p.h/2, halfLen=GRIP_LEN/2+HANDLE_PX*0.4, halfThick=GRIP_THICK/2+HANDLE_PX;
  const xLo=Math.max(p.x+GRIP_THICK/2+3, X(stepMin));
  const xHi=X(stepMax);
  const yBot=roll.size().h-GRIP_THICK/2-6;   // STICKY: pinned to the viewport bottom, always present
  if (Math.abs(x-xLo)<=halfThick && Math.abs(y-yMid)<=halfLen) return 'pmin';
  if (Math.abs(x-xHi)<=halfThick && Math.abs(y-yMid)<=halfLen) return 'pmax';
  if (Math.abs(y-yBot)<=halfThick && Math.abs(x-(p.x+p.w/2))<=halfLen) return 'tbottom';
  return null;
}
// Time-bottom handle is CLICK-to-extend (not drag): each click adds one avartana
// (or 8 units with no tala) of empty grid and scrolls the roll so the new bottom —
// with the handle on it — sits near the viewport bottom, ready for the next click.
function extendTime(){ const inc=talaMeasure>0?talaMeasure:8;
  userGridBottom=(userGridBottom!=null?userGridBottom:TOTAL)+inc;
  recomputeGridBounds(); resizeCanvas();
  const hd=document.getElementById('holder');
  hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), PAD.t + TOTAL*pxU() - (hd.clientHeight-40)));
  render(); }
function startHandleDrag(which,e){ const {x}=evtPos(e);
  handleDrag={ which, pid:e.pointerId, startX:x, startStepMin:stepMin, startStepMax:stepMax,
    pxPerStep: plot().w/Math.max(1,(stepMax-stepMin)) };   // FROZEN px-per-step at grab start
  cv.style.touchAction='none'; try{ cv.setPointerCapture(e.pointerId); }catch(_){}; render(); }
// Position the draggable A/B gutter handles at their marker times. The gutter is
// absolute-in-content (scrolls with the roll), so handles sit at VIRTUAL y and stay
// aligned with their marker lines as you scroll.
function positionHandles(){ const g=$('gutter'); if (mode!=='roll'){ g.style.display='none'; return; } g.style.display='';
  $('mkA').style.top=yVirt(markerA)+'px'; $('mkB').style.top=yVirt(markerB)+'px'; }
function roundRect(x,y,w,h,r){ r=Math.min(r,w/2,h/2); ctx.beginPath(); ctx.moveTo(x+r,y); ctx.arcTo(x+w,y,x+w,y+h,r); ctx.arcTo(x+w,y+h,x,y+h,r); ctx.arcTo(x,y+h,x,y,r); ctx.arcTo(x,y,x+w,y,r); ctx.closePath(); }

// ---------- interaction ----------
function evtPos(e){ const r=cv.getBoundingClientRect(); return { x:e.clientX-r.left, y:e.clientY-r.top }; }
// roll: selection is a click/tap (so a drag can scroll the tall roll)
let dEdit=null;   // draw-mode curve gesture: {downX,downY,hi,origCurve,mode:'pending'|'drag'|'free'}
const DEDIT_EPS=6;
// Is (x,y) on the selected note's curve LINE (draw-mode coords), for tap-to-add?
function onCurveLineDraw(x,y){ const c=NOTES[sel].curve; if (!c) return false; const [t0,t1]=yStartEnd();
  const u=Math.max(0,Math.min(1,(tAtY(y)-t0)/Math.max(1e-6,t1-t0))); const st=sampleCurve(c,u); return Math.abs(X(st)-x)<=14; }
cv.addEventListener('pointerdown', e=>{ if (mode!=='draw') return; try{ cv.setPointerCapture(e.pointerId); }catch(_){} ; ensureAudio(); const {x,y}=evtPos(e);
  dEdit={ downX:x, downY:y, hi:(NOTES[sel].curve?hitHandle(x,y):-1), origCurve:(NOTES[sel].curve?NOTES[sel].curve.map(p=>p.slice()):null), mode:'pending' }; });
cv.addEventListener('pointermove', e=>{ if (mode!=='draw' || !dEdit) return; const {x,y}=evtPos(e);
  if (dEdit.mode==='pending' && (Math.abs(x-dEdit.downX)>DEDIT_EPS || Math.abs(y-dEdit.downY)>DEDIT_EPS)){
    if (dEdit.hi>=0){ pushUndo(); dEdit.mode='drag'; dragIdx=dEdit.hi; liveOn(); liveSet(NOTES[sel].curve[dEdit.hi][1]); }
    else { pushUndo(); dEdit.mode='free'; drawing=true; NOTES[sel].curve=[]; liveOn(); addPoint(x,y); render(); return; } }
  if (dEdit.mode==='drag'){ dragHandle(x,y); render(); return; }
  if (dEdit.mode==='free'){ addPoint(x,y); render(); return; } });
cv.addEventListener('pointerup', e=>{ if (mode!=='draw' || !dEdit) return; const {x,y}=evtPos(e); const g=dEdit; dEdit=null;
  if (g.mode==='drag'){ if (document.getElementById('snap').checked) NOTES[sel].curve[dragIdx][1]=snapStep(NOTES[sel].curve[dragIdx][1]); dragIdx=-1; liveOff(); render(); autoPlay(); scheduleShare(); return; }
  if (g.mode==='free'){ drawing=false; liveOff(); finalizeCurve(); render(); autoPlay(); scheduleShare(); return; }
  // tap (no drag): on a handle -> remove; on the curve line -> add
  if (g.hi>=0){ pushUndo(); NOTES[sel].curve=removeAnchor(NOTES[sel].curve, g.hi);
    const has=!!(NOTES[sel].curve&&NOTES[sel].curve.length); document.getElementById('clear').disabled=!has; document.getElementById('copy').disabled=!has;
    liveOff(); render(); autoPlay(); scheduleShare(); return; }
  if (NOTES[sel].curve && onCurveLineDraw(x,y)){ pushUndo(); const [t0,t1]=yStartEnd();
    const u=Math.max(0,Math.min(1,(tAtY(y)-t0)/Math.max(1e-6,t1-t0))); const st=document.getElementById('snap').checked ? snapStep(Math.round(stepAtX(x))) : Math.round(stepAtX(x));
    NOTES[sel].curve=addAnchor(NOTES[sel].curve, u, st); render(); autoPlay(); scheduleShare(); return; }
  liveOff(); });
cv.addEventListener('pointercancel', ()=>{ if (dEdit){ if (dEdit.mode!=='pending') NOTES[sel].curve=dEdit.origCurve; dEdit=null; } drawing=false; dragIdx=-1; liveOff(); render(); });
// The pointer gestures live in core/roll-edit.js: it decides what a press MEANS and
// emits an intent. What an edit costs — undo, re-serialising the notation, rebuilding
// the model — is decided here, because that is draw's answer and not every host's.
//
// preview: in flight, shown but not recorded. commit: recorded. cancel: put it back.
const rollEdit = createRollEdit(cv, {
  geometry: () => geo(),
  model: () => ({ notes: NOTES, starts, rests: RESTS, stepMin, stepMax }),
  snapStep: (step) => snapToRagaRow(step, ragaRowSteps()),
  snapDur: (d) => { const beat = talaBeat || 1; return Math.max(beat, snapToAkshara(d, beat)); },
  snapTime: (t) => snapToAkshara(t, talaBeat || 1),
  redraw: () => render(),
  enabled: () => mode === 'roll' && !paintMode && !gamakaMode,
  idleTouchAction: ROLL_TOUCH_ACTION,
  onGrabStart: () => ensureAudio(),
  emit: (it) => applyIntent(it),
});

// The grid stretch-handles are draw's, not the roll's — they resize the VIEW, not the
// music. Capture phase so a press on a handle is claimed before roll-edit reads it as
// a note.
cv.addEventListener('pointerdown', e=>{ if (mode!=='roll' || paintMode || gamakaMode) return;
  const {x,y}=evtPos(e); const gh=hitGridHandle(x,y); if (!gh) return;
  e.stopPropagation();
  if (gh==='tbottom') extendTime(); else startHandleDrag(gh,e);
}, true);

// Whatever ends where this note begins — a note or a rest. Token order is the
// composition's order, rests included, so the neighbour is simply the highest tok
// below this one.
function prevElement(tok) {
  let best = null;
  for (const n of NOTES) if (n.tok < tok && (!best || n.tok > best.tok)) best = { tok: n.tok, rest: false, dur: n.dur, t0: starts[NOTES.indexOf(n)], step: n.step, curve: n.curve };
  for (const r of RESTS) if (r.tok < tok && (!best || r.tok > best.tok)) best = { tok: r.tok, rest: true, dur: r.dur, t0: r.t0, step: 0, curve: null };
  return best;
}

// The seam drag in flight: the contour as it was when the pointer went down, plus
// what to put back if the gesture dies.
let seamDrag = null;
function restoreSeam() {
  if (!seamDrag) return;
  const d = seamDrag, i = NOTES.findIndex((x) => x.tok === d.tok);
  const pn = d.prev.rest ? null : NOTES.find((x) => x.tok === d.prev.tok);
  const pr = d.prev.rest ? RESTS.find((x) => x.tok === d.prev.tok) : null;
  if (pn) { pn.dur = d.was.prevDur; pn.curve = d.was.prevCurve; }
  if (pr) pr.dur = d.was.prevDur;
  if (i >= 0) { NOTES[i].dur = d.was.dur; NOTES[i].curve = d.was.curve; starts[i] = d.was.t0; }
  seamDrag = null;
}

const INTENT_LOG = [];              // headless guards read this; nothing else does
async function applyIntent(it) {
  INTENT_LOG.push({ ...it }); if (INTENT_LOG.length > 200) INTENT_LOG.shift();
  if (it.kind === 'select') {
    selRest = it.target && it.target.type === 'rest' ? it.target.tok : -1;
    syncDelete(); render(); return;
  }
  if (it.kind === 'open') { selRest = -1; syncDelete(); enterDraw(it.index); return; }

  const n = NOTES.find((x) => x.tok === it.tok);
  const r = RESTS.find((x) => x.tok === it.tok);

  if (it.kind === 'move') {
    if (!n) return;
    if (it.phase !== 'commit') { n.step = it.step; render(); return; }
    pushUndo(); await onMoveDrop(NOTES.indexOf(n), it.from);
    return;
  }
  // The near edge moves the SEAM between this note and whatever ran up to it — and
  // the sound across the pair does not change. The pair is one pitch contour; the drag
  // only moves where it stops being written as one note and starts being written as
  // the next. Pull it far enough and the first note is gone, its line preserved inside
  // this one's gamaka. That is the repair for a detector that split one sung phrase in
  // two, which is most of what pitchy's over-segmentation produces.
  //
  // The contour is captured ONCE, when the drag starts. Re-reading it from notes that
  // have already been re-split would fold each preview's rounding into the next.
  if (it.kind === 'boundary') {
    const i = NOTES.indexOf(n);
    if (i < 0) return;
    if (it.phase === 'cancel') { restoreSeam(); render(); return; }

    if (!seamDrag || seamDrag.tok !== it.tok) {
      const prev = prevElement(it.tok);
      if (!prev) { seamDrag = null; return; }        // nothing before it: no seam to move
      const before = prev.rest ? prevElement(prev.tok) : null;
      seamDrag = {
        tok: it.tok, prev,
        t0: prev.t0, end: starts[i] + NOTES[i].dur,
        prevStep: prev.rest ? NOTES[i].step : prev.step,
        nextStep: NOTES[i].step,
        // When the neighbour is a REST, the note before IT comes along as context —
        // not as something this drag can change, but because bridging the silence
        // needs the pitch the line left off at. Without it the gap has only one end
        // and the best it could do is hold this note's opening pitch backwards.
        points: anchorsOf([
          ...(prev.rest && before ? [{ t0: before.t0, dur: before.dur, step: before.step, curve: before.curve, rest: before.rest }] : []),
          { t0: prev.t0, dur: prev.dur, step: prev.step, curve: prev.curve, rest: prev.rest },
          { t0: starts[i], dur: NOTES[i].dur, step: NOTES[i].step, curve: NOTES[i].curve },
        ]),
        was: { prevDur: prev.dur, prevCurve: prev.curve, dur: NOTES[i].dur, curve: NOTES[i].curve, t0: starts[i] },
      };
    }
    const d = seamDrag;
    const beat = talaBeat || 1;
    const out = resplitAt({ points: d.points, t0: d.t0, end: d.end, seam: it.t0,
      prevStep: d.prevStep, nextStep: d.nextStep, minDur: beat });

    const prevNote = d.prev.rest ? null : NOTES.find((x) => x.tok === d.prev.tok);
    const prevRest = d.prev.rest ? RESTS.find((x) => x.tok === d.prev.tok) : null;

    if (it.phase !== 'commit') {
      // Shown, not recorded. A fully absorbed neighbour is drawn as nothing rather
      // than removed, so the arrays keep their shape until the pointer is up.
      const pd = out.prev ? out.prev.dur : 0;
      if (prevNote) { prevNote.dur = pd; if (!d.prev.rest) prevNote.curve = out.prev ? out.prev.curve : prevNote.curve; }
      if (prevRest) prevRest.dur = pd;
      NOTES[i].dur = out.next.dur; NOTES[i].curve = out.next.curve;
      starts[i] = d.t0 + pd;
      render(); return;
    }

    pushUndo();
    const changed = new Set([it.tok]);
    if (!out.prev) {
      // Swallowed whole: the neighbour's token goes, its pitch already inside this
      // note's gamaka. deriveOctave, because a dropped token takes its octave marks
      // with it and the register must be re-stated for everything after.
      seamDrag = null;
      await commitEdit({ changed, deletes: new Set([d.prev.tok]), deriveOctave: true });
      return;
    }
    seamDrag = null;
    if (d.prev.rest) await commitEdit({ changed, deriveOctave: false, restDurs: new Map([[d.prev.tok, out.prev.dur]]) });
    else { changed.add(d.prev.tok); await commitEdit({ changed, deriveOctave: false }); }
    return;
  }
  if (it.kind === 'resize') {
    if (it.target === 'rest') {
      if (!r) return;
      if (it.phase !== 'commit') { r.dur = it.dur; render(); return; }
      pushUndo(); await commitRestDur(it.tok, it.dur);
      return;
    }
    if (!n) return;
    if (it.phase !== 'commit') { n.dur = it.dur; render(); return; }
    pushUndo(); await commitEdit({ changed: new Set([it.tok]), deriveOctave: false });
  }
}

// Paint mode (`+ note` toggled on): drag on the grid creates a note — pitch snaps to
// a raga row, length to the tala akshara. Capture-phase + the !paintMode guard on the
// grab handlers above keep paint and grab gestures mutually exclusive. `paint` tracks
// its owning pointerId (`pid`), same pattern as `grab`, so a second concurrent touch
// can't overwrite the in-progress gesture and corrupt the eventual commit.
cv.addEventListener('pointerdown', e=>{ if (mode!=='roll' || !paintMode) return;
  { const {x,y}=evtPos(e); const gh=hitGridHandle(x,y); if (gh){ if (gh==='tbottom') extendTime(); else startHandleDrag(gh,e); return; } }
  if (paint) return;   // a paint is already active (e.g. a second finger) — ignore
  ensureAudio();
  const {x,y}=evtPos(e); const beat=talaBeat||1;
  const ts=Math.max(0, snapToAkshara(tAtY(y), beat));
  const restLane = x < plot().x + REST_LANE_PX;
  if (restLane){ paint={ ts, rest:true, dur:beat, pid:e.pointerId }; }
  else { const step=snapToRagaRow(Math.round(stepAtX(x)), ragaRowSteps()); paint={ ts, step, dur:beat, pid:e.pointerId }; }
  try{ cv.setPointerCapture(e.pointerId); }catch(_){}; render(); }, true);
cv.addEventListener('pointermove', e=>{ if (!paint || e.pointerId!==paint.pid) return; const {y}=evtPos(e); const beat=talaBeat||1;
  paint.dur=Math.max(beat, snapToAkshara(tAtY(y)-paint.ts, beat)); render(); }, true);
cv.addEventListener('pointerup', async e=>{ if (!paint || e.pointerId!==paint.pid) return;
  if (!paintMode){ paint=null; render(); return; }   // Fix #7: `+ note` toggled off mid-drag — abort, don't commit
  const p=paint; paint=null;
  rollEdit.suppressClick();   // a painted note ends in a click ON it; that is not "open me"
  const durs=NOTES.map(n=>n.dur);
  const place=placePaint({ ts:p.ts, dur:p.dur, notes:NOTES, starts, durs, total:TOTAL });
  pushUndo(); await applyPaint(place, p); }, true);
// Defensive, mirroring the grab gesture's pointercancel: an OS-interrupted paint
// (app backgrounded mid-drag, etc.) must not leave `paint` set — that would render
// the green preview forever with no gesture left to dismiss it. Paint doesn't touch
// cv.style.cursor/touchAction per-gesture (unlike grab, which owns the drag axis),
// so there is nothing else to restore here beyond nulling the state and re-rendering.
cv.addEventListener('pointercancel', e=>{ if (!paint || e.pointerId!==paint.pid) return; paint=null; render(); }, true);
// In-roll gamaka drawing/editing (`✎ gamaka` toggled on). Grid handles + `+ time`
// are checked first (so you can zoom while editing). The note under the initial
// press is the stroke's target; drag on empty note area = freehand redraw.
const MOVE_EPS=6;   // px before a press counts as a drag (vs a tap)
function uAt(i,y){ return Math.max(0,Math.min(1,(tAtY(y)-starts[i])/Math.max(1e-6,NOTES[i].dur))); }
function stepAt(x){ const p=plot(); return snapStep(Math.round(stepAtX(Math.max(p.x,Math.min(p.x+p.w,x))))); }
// Roll-coord hit-test of note gi's anchors; returns the anchor index or -1.
function hitAnchor(gi,x,y){ const c=NOTES[gi].curve; if (!c) return -1; const t0=starts[gi],t1=t0+NOTES[gi].dur;
  for (let k=0;k<c.length;k++){ const cx=X(c[k][1]),cy=Y(t0+(t1-t0)*c[k][0]); if ((x-cx)*(x-cx)+(y-cy)*(y-cy)<=16*16) return k; } return -1; }
// Is (x,y) on note gi's curve LINE (within ~12px), for tap-to-add? Sample at the press u.
function onCurveLine(gi,x,y){ const c=NOTES[gi].curve; if (!c) return false; const u=uAt(gi,y);
  const st=sampleCurve(c,u); return Math.abs(X(st)-x)<=12; }
cv.addEventListener('pointerdown', e=>{ if (mode!=='roll' || !gamakaMode) return;
  { const {x,y}=evtPos(e); const gh=hitGridHandle(x,y); if (gh){ if (gh==='tbottom') extendTime(); else startHandleDrag(gh,e); return; } }
  if (gamaStroke) return;
  ensureAudio(); const {x,y}=evtPos(e); const i=hitNote(x,y); if (i<0) return;
  try{ cv.setPointerCapture(e.pointerId); }catch(_){};
  const dragIdx = NOTES[i].curve ? hitAnchor(i,x,y) : -1;
  gamaStroke={ gi:i, pid:e.pointerId, downX:x, downY:y, dragIdx, buffer:null, mode: dragIdx>=0 ? 'anchor' : 'pending', origCurve:NOTES[i].curve };
}, true);
cv.addEventListener('pointermove', e=>{ if (!gamaStroke || e.pointerId!==gamaStroke.pid) return; const {x,y}=evtPos(e);
  const g=gamaStroke;
  if (g.mode==='anchor'){ if (Math.abs(x-g.downX)>MOVE_EPS || Math.abs(y-g.downY)>MOVE_EPS){
      if (!g.moved){ pushUndo(); g.moved=true; }
      NOTES[g.gi].curve=moveAnchor(NOTES[g.gi].curve, g.dragIdx, uAt(g.gi,y), stepAt(x)); render(); }
    return; }
  if (g.mode==='pending' && (Math.abs(x-g.downX)>MOVE_EPS || Math.abs(y-g.downY)>MOVE_EPS)){
    // begin a freehand redraw of the target note's curve
    pushUndo(); g.mode='free'; g.buffer=[]; NOTES[g.gi].curve=null;
  }
  if (g.mode==='free'){ const u=uAt(g.gi,y), st=stepAt(x);
    if (g.buffer.length && u<=g.buffer[g.buffer.length-1][0]) g.buffer[g.buffer.length-1][1]=st; else g.buffer.push([u,st]);
    NOTES[g.gi].curve=g.buffer.slice(); render(); }
}, true);
cv.addEventListener('pointerup', e=>{ if (!gamaStroke || e.pointerId!==gamaStroke.pid) return; const g=gamaStroke; gamaStroke=null;
  rollEdit.suppressClick();   // suppress the trailing click (don't fall into the full-screen editor)
  const {x,y}=evtPos(e); const moved=Math.abs(x-g.downX)>MOVE_EPS||Math.abs(y-g.downY)>MOVE_EPS;
  if (g.mode==='free'){ NOTES[g.gi].curve=pointsToAnchors(g.buffer); render(); scheduleShare(); return; }
  if (g.mode==='anchor'){ if (g.moved){ scheduleShare(); }
    else { pushUndo(); NOTES[g.gi].curve=removeAnchor(NOTES[g.gi].curve, g.dragIdx); render(); scheduleShare(); }  // tap = remove
    return; }
  // mode 'pending' with no move: tap on the curve line adds an anchor there
  if (!moved && NOTES[g.gi].curve && onCurveLine(g.gi,x,y)){ pushUndo();
    NOTES[g.gi].curve=addAnchor(NOTES[g.gi].curve, uAt(g.gi,y), stepAt(x)); render(); scheduleShare(); }
}, true);
cv.addEventListener('pointercancel', e=>{ if (!gamaStroke || e.pointerId!==gamaStroke.pid) return; NOTES[gamaStroke.gi].curve=gamaStroke.origCurve; gamaStroke=null; render(); }, true);
// Grid stretch-handle drag (pitch-low/pitch-high/time-bottom). These are separate
// listeners (not folded into grab/paint) because a handle-drag must fire in BOTH
// normal and paint mode — startHandleDrag() is invoked from the top of both roll
// pointerdowns above, before their own mode-specific logic runs. No-op unless
// handleDrag is set, so they coexist peacefully with the grab/paint handlers.
cv.addEventListener('pointermove', e=>{ if (!handleDrag || e.pointerId!==handleDrag.pid) return; const {x,y}=evtPos(e);
  const hd=document.getElementById('holder'), content=document.getElementById('content');
  if (handleDrag.which==='tbottom'){
    userGridBottom=Math.max(snapToAkshara(tAtY(y), talaBeat||1), (talaBeat||1));
    recomputeGridBounds(); content.style.height=virtH()+'px';
    // Fix 3 scroll-follow: glue the bottom edge under the cursor so the new time is visible live.
    hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), PAD.t + TOTAL*pxU() - y));
  } else {
    // Frozen-scale: bound = start bound + cursor pixel-travel / start px-per-step. Independent of
    // the live (rescaling) stepMin/stepMax, so no feedback loop pins the value.
    const dSteps=(x-handleDrag.startX)/handleDrag.pxPerStep;
    const base=(handleDrag.which==='pmin')?handleDrag.startStepMin:handleDrag.startStepMax;
    const st=snapToRagaRow(Math.round(base+dSteps), ragaRowSteps());
    if (handleDrag.which==='pmin') userGridMin=st; else userGridMax=st;
    recomputeGridBounds(); content.style.height=virtH()+'px';
  }
  render(); });
cv.addEventListener('pointerup', e=>{ if (!handleDrag || e.pointerId!==handleDrag.pid) return; handleDrag=null; cv.style.touchAction=ROLL_TOUCH_ACTION; });
cv.addEventListener('pointercancel', e=>{ if (!handleDrag || e.pointerId!==handleDrag.pid) return; handleDrag=null; cv.style.touchAction=ROLL_TOUCH_ACTION; render(); });
// Discoverability: hover the grid stretch-handles shows a resize cursor (idle only —
// not while any drag/grab/paint gesture is in progress). No log param -> hitGridHandle
// stays silent here, so this high-frequency listener doesn't flood the console (Fix 5).
cv.addEventListener('pointermove', e=>{ if (mode!=='roll' || handleDrag || rollEdit.busy() || paint) return;
  const {x,y}=evtPos(e); const h=hitGridHandle(x,y);
  cv.style.cursor = h ? (h==='tbottom'?'pointer':'col-resize') : (paintMode?'crosshair':''); });
// A moved note is committed with the current gamaka-on-move default; if it carried
// a gamaka, a toast offers the other behaviour for ~4s. The model stores the curve
// ABSOLUTE, so 'preserve pitch' = leave the curve (serialize emits shifted relative
// deltas); 'move with note' = shift the abs curve by +Δstep so the relative deltas
// stay verbatim and the whole curve rides the note.
async function onMoveDrop(idx, oldStep){
  const n=NOTES[idx], dStep=n.step-oldStep;
  // Derive octave the same way the letter itself is derived (stepToSwara), not via
  // a raw Math.floor(step/EDO) — that disagrees with stepToSwara's c12 wrap-to-next-
  // octave behaviour near the top of an octave, which could spell the wrong octave.
  const ctx=ragaCtx();
  const newOct=stepToSwara(n.step, ctx).octave, oldOct=stepToSwara(oldStep, ctx).octave;
  n.octave=newOct;
  const hasCurve=!!(n.curve && n.curve.length);
  // Capture the mode once, before the await below — gmovesel can change live while
  // commitEdit is in flight, and the toast must describe/flip the mode that was
  // actually applied to this drop, not whatever the dropdown reads afterward.
  const appliedMode=gamakaOnMove;
  const applyMode=(mode)=>{ if (!hasCurve) return;
    // The abs curve is left exactly as it was pre-drop; the mode only decides
    // whether to shift it by dStep so it rides the note (move-with-note) or
    // stays put so the note's pitch through the curve is unchanged (preserve-pitch).
    if (mode==='move-with-note') n.curve=n.curve.map(([u,s])=>[u,s+dStep]);
    /* preserve-pitch: leave abs curve as-is */ };
  applyMode(appliedMode);
  await commitEdit({ changed:new Set([n.tok]), deriveOctave:newOct!==oldOct });
  if (!hasCurve) return;
  const other=appliedMode==='preserve-pitch'?'move-with-note':'preserve-pitch';
  const label=appliedMode==='preserve-pitch'?'move with note':'preserve pitch';
  showToast(`Gamaka: ${appliedMode==='preserve-pitch'?'pitch preserved':'moved with note'}`, `switch to ${label}`, async ()=>{
    // Flip: after buildModel, re-find the note by its tok and reshift the abs curve
    // by the opposite of what appliedMode implied, then re-commit.
    const j=NOTES.findIndex(x=>x.tok===n.tok); if (j<0) return; const m=NOTES[j];
    if (!m.curve || !m.curve.length) return;
    if (other==='move-with-note') m.curve=m.curve.map(([u,s])=>[u,s+dStep]);
    else m.curve=m.curve.map(([u,s])=>[u,s-dStep]);
    pushUndo(); await commitEdit({ changed:new Set([m.tok]), deriveOctave:false }); });
}
// Build the serializeModel insert for a painted note or rest. For 'split', the host
// is cut into a HEAD (kept by the host token) and a TAIL continuation (same pitch,
// inserted after the new item) via splitSpans — this preserves the host's original
// sustain instead of discarding it. For 'fill'/'append' the item lands at the
// DRAGGED time `p.ts`, not just after the anchor — a leading rest is inserted ahead
// of it whenever there's a time gap (append past the true content end, or fill/split
// before the very first note, via serializeModel's `inserts.get(-1)` prepend).
async function applyPaint(place, p){
  const item = p.rest ? { rest:true, dur:p.dur }
    : { step:p.step, octave:Math.floor(p.step/EDO)+5, dur:p.dur, curve:null };
  const model=modelByTok(); const changed=new Set(); const inserts=new Map();
  if (place.kind==='append' && place.anchorTok<0){        // empty piece: seed directly in srcText
    const lead = p.ts>0 ? ('z'+(Math.round(p.ts)>1?Math.round(p.ts):'')+' ') : '';
    const len=Math.max(1,Math.round(p.dur));
    // Octave marks are needed here (unlike commitEdit's derived path) because this
    // branch writes srcText directly, bypassing serializeModel's deriveOctave — the
    // blank skeleton's O=5 baseline means a bare letter always parses back to octave
    // 5, silently flattening a note painted in an upper/lower row (Fix 1).
    const sw = stepToSwara(p.step, ragaCtx());
    const body = len > 1 ? String(len) : '';
    const tok = p.rest ? ('z' + body) : (octMarks(sw.octave - 5) + sw.letter + body);   // bare swara/z when len===1 (Task 3 convention)
    buildModel(srcText.replace(/\s*$/,'') + '\n' + lead + tok + '\n');
    syncControls(); resizeCanvas(); render(); await rebuildShare(); return; }
  if (place.kind==='split'){
    const hostIdx=NOTES.findIndex(n=>n.tok===place.host);
    const host=model.get(place.host);
    const { head, tail }=splitSpans(starts[hostIdx], host.dur, p.ts, p.dur);
    if (head<=0){
      // Degenerate: paint lands at/before the host's own start — a zero-length head
      // would emit a bogus token. Insert BEFORE the host instead (anchor on the
      // previous surviving note), or — no previous note — prepend via inserts.get(-1),
      // with a leading rest if `p.ts` is after the very start of the piece.
      if (hostIdx>0) inserts.set(NOTES[hostIdx-1].tok, [item]);
      else inserts.set(-1, p.ts>0 ? [{rest:true,dur:p.ts}, item] : [item]);
    } else {
      host.dur=head; changed.add(place.host);
      // Tail continuation carries the host's original remainder onward, same pitch,
      // no gamaka curve of its own — only emitted when there IS a remainder.
      const tailNote = tail>0 ? { step:host.step, octave:host.octave, dur:tail, curve:null } : null;
      inserts.set(place.host, tailNote ? [item, tailNote] : [item]);
    }
  } else if (place.kind==='append'){                       // append past the true content end
    const gap = Math.round(p.ts - contentEnd);
    inserts.set(place.anchorTok, gap>0 ? [{rest:true,dur:gap}, item] : [item]);
  } else if (place.anchorTok<0){                            // fill: before the very first note
    const lead = p.ts>0 ? [{rest:true, dur:p.ts}] : [];
    inserts.set(-1, [...lead, item]);
  } else {                                                   // fill: mid-piece
    inserts.set(place.anchorTok, [item]);
  }
  const newSrc=serializeModel(srcText, { model, changed, inserts, deletes:new Set(), deriveOctave:true, ctx:ragaCtx() });
  buildModel(newSrc); syncControls(); resizeCanvas(); render(); await rebuildShare();
}
// A rest spans the width, so anywhere on its band selects it — the same target the
// eye sees. Notes are tested first: where a note box overlaps a rest band, the note
// is what you meant.
// Hit-testing lives with the gestures now (core/roll-edit.js); the paint and gamaka
// paths still ask for it here.
const hitNote = (x,y) => rollEdit.hitNote(x,y);
function addPoint(x,y){ const p=plot(),[ba,bb]=yStartEnd();
  let u=Math.max(0,Math.min(1,(tAtY(y)-ba)/(bb-ba)));
  const st=stepAtX(Math.max(p.x,Math.min(p.x+p.w,x)));
  const c=NOTES[sel].curve; if (c.length&&u<=c[c.length-1][0]) c[c.length-1][1]=st; else c.push([u,st]);
  liveSet(st); document.getElementById('read').textContent='≈'+freqOf(st).toFixed(0)+' Hz'; }
function finalizeCurve(){ let c=NOTES[sel].curve; if (!c||c.length<2){ NOTES[sel].curve=null; document.getElementById('clear').disabled=true; document.getElementById('copy').disabled=true; return; }
  c=extractAnchors(c);
  if (document.getElementById('snap').checked) c=c.map(pt=>[pt[0],snapStep(pt[1])]);
  if (c[0][0]>0.001) c=[[0,c[0][1]],...c];
  if (c[c.length-1][0]<0.999) c=[...c,[1,c[c.length-1][1]]];
  NOTES[sel].curve=c; document.getElementById('clear').disabled=false; document.getElementById('copy').disabled=false; }
function hitHandle(x,y){ const c=NOTES[sel].curve; if (!c) return -1; const [t0,t1]=yStartEnd();
  for (let k=0;k<c.length;k++){ const cx=X(c[k][1]),cy=Y(t0+(t1-t0)*c[k][0]); if ((x-cx)*(x-cx)+(y-cy)*(y-cy)<=18*18) return k; } return -1; }
function dragHandle(x,y){ const c=NOTES[sel].curve,p=plot(),[ba,bb]=yStartEnd();
  let u=(tAtY(y)-ba)/(bb-ba); const lo=dragIdx===0?0:c[dragIdx-1][0]+0.006, hi=dragIdx===c.length-1?1:c[dragIdx+1][0]-0.006;
  u=Math.max(lo,Math.min(hi,u)); const st=stepAtX(Math.max(p.x,Math.min(p.x+p.w,x)));
  c[dragIdx][0]=u; c[dragIdx][1]=st; liveSet(st); document.getElementById('read').textContent='≈'+freqOf(st).toFixed(0)+' Hz'; }

const $ = id => document.getElementById(id);
let clipRel=null;   // copied curve, stored RELATIVE to its note's step (so it re-anchors on paste)
function enterDraw(i){ sel=i; mode='draw'; syncDelete();
  $('mode').textContent='draw the curve'; $('crumb').textContent='note '+(i+1)+' · '+NOTES[i].swara+NOTES[i].octave;
  for (const b of ['clear','copy','paste','back']) $(b).style.display='';   // draw-only buttons appear
  $('back').disabled=false; $('clear').disabled=!NOTES[i].curve; $('copy').disabled=!NOTES[i].curve; $('paste').disabled=!clipRel;
  setPlayBtn('▶','Play note'); $('rangectl').style.display=''; $('snapctl').style.display=''; $('tzoom').style.display='none'; resizeCanvas(); }
$('back').onclick=()=>{ dEdit=null; drawing=false; dragIdx=-1; mode='roll'; sel=-1; syncDelete(); $('mode').textContent='select a note'; $('crumb').textContent='';
  for (const b of ['clear','copy','paste','back']) $(b).style.display='none';   // draw-only buttons hidden in roll mode
  $('read').textContent=''; setPlayBtn('▶',playLabel());
  $('rangectl').style.display='none'; $('snapctl').style.display='none'; $('tzoom').style.display=''; resizeCanvas(); };
$('clear').onclick=()=>{ if (sel>=0 && NOTES[sel].curve){ pushUndo(); NOTES[sel].curve=null; $('clear').disabled=true; $('copy').disabled=true; render(); scheduleShare(); } };
function flashBtn(id,msg){ const b=$(id),t=b.textContent; b.textContent=msg; setTimeout(()=>b.textContent=t,1100); }
// Copy stores the curve relative to its note's step; Paste re-anchors it (transpose
// only — preserves the copied shape/tuning exactly), plays the target for feedback.
function copyFrom(i){ if (!NOTES[i].curve) return; const s0=NOTES[i].step; clipRel=NOTES[i].curve.map(([u,s])=>[u, s-s0]); $('paste').disabled=false; }
function pasteTo(i){ if (!clipRel) return; const s0=NOTES[i].step; NOTES[i].curve=clipRel.map(([u,d])=>[u, s0+d]);
  if (sel===i){ $('clear').disabled=false; $('copy').disabled=false; } render(); scheduleShare(); playNote(i); }
$('copy').onclick=()=>{ if (sel>=0&&NOTES[sel].curve){ copyFrom(sel); flashBtn('copy','Copied'); } };
$('paste').onclick=()=>{ if (sel>=0) pasteTo(sel); };
// desktop: right-click / ctrl-click a note in the roll to copy or paste its gamaka
let ctxNote=-1;
// Play button shows only an icon (compact on mobile); the words go in its title.
function setPlayBtn(icon, title){ const b=$('play'); b.textContent=icon; b.title=title; }
function setPlayIdle(){ if (!playing&&!paused) setPlayBtn('▶', playLabel()); }
cv.addEventListener('contextmenu', e=>{ if (mode!=='roll') return; e.preventDefault(); const {x,y}=evtPos(e);
  ctxNote=hitNote(x,y); ctxTime=Math.max(0,Math.min(TOTAL,tAtY(y))); const cm=$('ctxmenu');
  cm.querySelector('[data-act=copy]').disabled=!(ctxNote>=0&&NOTES[ctxNote].curve);
  cm.querySelector('[data-act=paste]').disabled=!(ctxNote>=0&&clipRel);
  cm.querySelector('[data-act=clearmk]').disabled=(markerA<=0.01&&markerB>=TOTAL-0.01);
  cm.style.left=Math.min(e.clientX, window.innerWidth-170)+'px'; cm.style.top=Math.min(e.clientY, window.innerHeight-210)+'px'; cm.style.display='block'; });
function hideCtx(){ $('ctxmenu').style.display='none'; }
$('ctxmenu').addEventListener('click', e=>{ const act=e.target.getAttribute&&e.target.getAttribute('data-act'); if (!act){ hideCtx(); return; }
  if (act==='copy'&&ctxNote>=0) copyFrom(ctxNote);
  else if (act==='paste'&&ctxNote>=0) pasteTo(ctxNote);
  else if (act==='seta'){ markerA=ctxTime; setPlayIdle(); render(); }
  else if (act==='setb'){ markerB=ctxTime; setPlayIdle(); render(); }
  else if (act==='clearmk'){ markerA=0; markerB=TOTAL; setPlayIdle(); render(); }
  else if (act==='playfrom'){ playFrom(ctxTime, (markerB!=null&&markerB>ctxTime)?markerB:TOTAL); }
  hideCtx(); });
// Draggable A/B gutter handles — grab and slide to set the play segment bounds.
function startMk(which){ return e=>{ e.preventDefault(); e.stopPropagation(); markerDrag=which; try{ $('mk'+which).setPointerCapture(e.pointerId); }catch(_){} }; }
$('mkA').addEventListener('pointerdown', startMk('A'));
$('mkB').addEventListener('pointerdown', startMk('B'));
window.addEventListener('pointermove', e=>{ if (!markerDrag) return; const r=cv.getBoundingClientRect();
  const t=Math.max(0,Math.min(TOTAL, tAtY(e.clientY-r.top))); if (markerDrag==='A') markerA=t; else markerB=t; setPlayIdle(); render(); });
window.addEventListener('pointerup', ()=>{ markerDrag=null; });
document.addEventListener('pointerdown', e=>{ if (!$('ctxmenu').contains(e.target)) hideCtx(); });
document.addEventListener('keydown', e=>{ if (e.key==='Escape') hideCtx(); });
$('holder').addEventListener('scroll', ()=>{ hideCtx(); if (mode==='roll') render(); });   // windowed roll: redraw the visible slice
// help popup
$('helpbtn').onclick=()=>{ const h=$('helppop'); h.hidden=!h.hidden; };
$('helpclose').onclick=()=>{ $('helppop').hidden=true; };
document.addEventListener('pointerdown', e=>{ const h=$('helppop'); if (!h.hidden && !h.contains(e.target) && e.target.id!=='helpbtn') h.hidden=true; });
document.addEventListener('keydown', e=>{ if (e.key==='Escape') $('helppop').hidden=true; });
$('rmin').onclick=()=>{ drawSpan=Math.max(10,drawSpan-8); resizeCanvas(); };
$('rplus').onclick=()=>{ drawSpan=Math.min(60,drawSpan+8); resizeCanvas(); };   // 60 ≈ a bit over an octave (53-EDO) each side
// Expand: scale up the roll (taller cells). Windowing means any zoom is safe — the
// canvas stays viewport-sized; only the scroll range grows. 1 = fully expanded floor.
$('tmin').onclick=()=>{ zoom=Math.max(1, Math.round((zoom-0.5)*10)/10); resizeCanvas(); };
$('tplus').onclick=()=>{ zoom=Math.min(8, Math.round((zoom+0.5)*10)/10); resizeCanvas(); };
// `+ note` toggle: paint mode is mutually exclusive with the roll's long-press grab
// (both handlers guard on paintMode, see the pointerdown listeners above), and with
// `✎ gamaka` mode below.
$('paintbtn').onclick=()=>{ paintMode=!paintMode; if (paintMode){ gamakaMode=false; $('gamakabtn').classList.remove('on'); if (gamaStroke){ NOTES[gamaStroke.gi].curve=gamaStroke.origCurve; gamaStroke=null; } }
  $('paintbtn').classList.toggle('on',paintMode); cv.style.cursor=paintMode?'crosshair':''; render(); };
// `✎ gamaka` toggle: shows draggable anchor dots on the roll (rendered in render()) and
// is mutually exclusive with `+ note` paint mode. Pointer handlers land in later tasks.
$('gamakabtn').onclick=()=>{ gamakaMode=!gamakaMode; if (gamakaMode){ paintMode=false; $('paintbtn').classList.remove('on'); }
  if (gamaStroke){ NOTES[gamaStroke.gi].curve=gamaStroke.origCurve; gamaStroke=null; } $('gamakabtn').classList.toggle('on',gamakaMode); cv.style.cursor=gamakaMode?'crosshair':''; render(); };
// Gamaka-on-move default: 'preserve pitch' (leave the abs curve — serialize emits shifted
// relative deltas) or 'move with note' (shift the abs curve so the deltas stay verbatim
// and the curve rides the note). Persisted; the post-move toast always offers the other.
const GKEY='ragamroll.gamakaOnMove';
let gamakaOnMove=localStorage.getItem(GKEY)||'preserve-pitch';
$('gmovesel').value=gamakaOnMove;
$('gmovesel').onchange=e=>{ gamakaOnMove=e.target.value; try{ localStorage.setItem(GKEY,gamakaOnMove); }catch(_){}; };
// Non-blocking toast: ~4s auto-dismiss, optional one-tap action.
let toastTimer=0;
function showToast(msg, actionLabel, onAction){ const t=$('toast'); t.innerHTML='';
  t.append(document.createTextNode(msg));
  if (actionLabel){ const b=document.createElement('button'); b.textContent=actionLabel;
    b.onclick=()=>{ hideToast(); onAction(); }; t.append(b); }
  t.style.display='flex'; clearTimeout(toastTimer); toastTimer=setTimeout(hideToast,4000); }
function hideToast(){ $('toast').style.display='none'; }
// Drone/tala levels are LIVE: each routes through a per-session gain bus, so a
// slider change scales the currently-playing drone / accent strums immediately.
$('dronevol').oninput=e=>{ droneVol=Number(e.target.value); if (audio) audio.setMix({ drone:droneVol }); };
$('talavol').oninput=e=>{ talaVol=Number(e.target.value); if (audio) audio.setMix({ tala:talaVol }); };
// Footer build/version — mirrors the app's Footer component (build-app-v0.sh stamps both).
$('footbuild').innerHTML=(BUILD_DATE?`built ${BUILD_DATE} · `:'')+`<span class="ver">${VERSION}</span>`;

// Sa reference pitch (playback transpose) — Auto = the composition's Sa (saRef).
// Changing it retunes saFreq only; the roll layout (steps) is anchored to saRef.
(function fillSa(){ let opts='<option value="">Auto</option>'; for (let m=40;m<=72;m++) opts+=`<option value="${m}">${midiToName(m)}</option>`; $('sapick').innerHTML=opts; })();
$('sapick').onchange=e=>{ saPlay=e.target.value===''?null:Number(e.target.value); saFreq=midiToFreq(saPlay==null?saRef:saPlay); render(); };
// Tempo slider — a multiplier of the composition tempo; affects playback speed only
// (the roll layout is in length-units, independent of tempo).
$('tempo').oninput=e=>{ tempoBpm=Math.round(compTempo*Number(e.target.value)); $('tempolbl').textContent=tempoBpm+' BPM'; };
// Sync the Sa / tempo controls to the current model (after a load/reload).
function syncControls(){ $('sapick').value=saPlay==null?'':String(saPlay);
  const auto=$('sapick').querySelector('option[value=""]'); if (auto) auto.textContent='Auto ('+midiToName(saRef)+')';
  $('tempo').value=String(Math.max(0.5,Math.min(2, tempoBpm/compTempo))); $('tempolbl').textContent=tempoBpm+' BPM';
  $('rt').textContent = curRaga ? `${curRaga} · ${curTala}` : '';
  // Raga/tala pickers apply only to a BLANK piece (no notes) — lock once notes exist.
  const blank = NOTES.length===0;
  $('ragasearch').disabled=!blank; $('talasel').disabled=!blank;
  $('editnote').textContent = blank ? 'pick a raga / tala, then type swaras below' : 'raga · tala locked while notes exist';
  $('ragasearch').value = curRaga || ''; $('talasel').value = curTalaName; }
// The per-raga seed map (drafts.json), fetched once. Tries the deployed path
// (./ragas/) then the local-curation path (../tools/out/); empty map if neither
// is reachable (offline / not built) — seeding then falls back to the plain scale.
let _draftsPromise = null;
function loadDrafts(){
  if (!_draftsPromise) _draftsPromise = (async () => {
    for (const url of ['./ragas/drafts.json', '../tools/out/drafts.json']) {
      try { const r = await fetch(url); if (r.ok) return await r.json(); } catch(_){}
    }
    _draftsPromise = null; // total failure (offline / not built) — don't memoize {}, retry next pick
    return {};
  })();
  return _draftsPromise;
}
// Set the Raga=/Tala= directive in the srgm (blank pieces only) and reload.
// A Raga pick seeds the piece with that raga's notation (curated draft, else a
// plain scale); a Tala pick only rewrites the directive (unchanged behaviour).
async function applyRagaTala(kind, name){ if (NOTES.length || !name) return;
  if (kind==='Raga'){
    // #ragasearch is free-text; canonicalize once so a non-canonical typed
    // case (e.g. "Mohanam") still hits drafts[name]/getRagaExt/getRagas().
    const cname = resolveRagaName(name) || name;
    const drafts = await loadDrafts();
    if (NOTES.length) return; // piece may no longer be blank after the async fetch
    const picked = chooseSeed(cname, drafts, getRagaExt(cname), getRagas());
    // seed the piece with the raga's notation, else fall back to a bare blank with Raga= set
    const seed = picked ? picked.srgm : `Raga=${cname},0\nTala=adi,4\nO=5 L=1\n`;
    loadSrc(seed, docName); setEditorH(editorH>10?editorH:Math.round((window.innerHeight||600)*0.35)); return;
  }
  // Tala (blank only): rewrite the Tala= directive and reload (unchanged behaviour)
  let s=srcText; const nv='Tala='+name+',4'; const re=/(^|\s)Tala=\S+/;
  s = re.test(s) ? s.replace(re, (m,p)=>p+nv) : nv+'\n'+s;
  loadSrc(s, docName); setEditorH(editorH>10?editorH:Math.round((window.innerHeight||600)*0.35));
}
// Back to the app: carry the composition CURRENTLY open here into the app (it reads
// the same localStorage key), so the app opens the same piece — not whatever it held.
$('backapp').onclick=e=>{ e.preventDefault(); try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}; location.href='./index.html'; };
// srgm editor: a slide-up panel below the buttons. Drag the grip to resize; tap to
// toggle. Native ctrl-z works for typing; edits reparse (debounced) → rebuild roll.
let editorH=0, gripDrag=null;
function setEditorH(h){ editorH=Math.max(0, Math.min(h, Math.round((window.innerHeight||600)*0.6)));
  $('editpanel').style.height=editorH+'px';
  if (editorH>0 && document.activeElement!==$('editor')) $('editor').value=srcText;
  requestAnimationFrame(resizeCanvas); }
$('grip').addEventListener('pointerdown', e=>{ e.preventDefault(); try{ $('grip').setPointerCapture(e.pointerId); }catch(_){}; gripDrag={y:e.clientY,h:editorH,moved:false}; });
$('grip').addEventListener('pointermove', e=>{ if (!gripDrag) return; const dy=gripDrag.y-e.clientY; if (Math.abs(dy)>3) gripDrag.moved=true; setEditorH(gripDrag.h+dy); });
$('grip').addEventListener('pointerup', ()=>{ if (gripDrag&&!gripDrag.moved) setEditorH(editorH>10?0:Math.round((window.innerHeight||600)*0.35)); gripDrag=null; });
$('editor').addEventListener('input', ()=>{ clearTimeout(editTimer); editTimer=setTimeout(onEditorInput, 300); });
$('ragasearch').onchange=()=>applyRagaTala('Raga', $('ragasearch').value.trim());
$('talasel').onchange=()=>applyRagaTala('Tala', $('talasel').value);
// Fullscreen toggle — on mobile this hides the browser address bar.
$('fsbtn').onclick=()=>{ const d=document, el=d.documentElement;
  if (!d.fullscreenElement && !d.webkitFullscreenElement){ (el.requestFullscreen||el.webkitRequestFullscreen||(()=>{})).call(el); }
  else { (d.exitFullscreen||d.webkitExitFullscreen||(()=>{})).call(d); } };
document.addEventListener('fullscreenchange', ()=>setTimeout(fit,100));

// ---------- audio ----------
let AC=null, live=null;
let droneVol=0.5, talaVol=0.5;   // 0..1; live via the per-session dBus/tBus gains
function ensureAudio(){ if (!AC){ try{ AC=new (window.AudioContext||window.webkitAudioContext)(); }catch(e){ return null; } }
  if (AC.state==='suspended') AC.resume();
  if (!live){ const osc=AC.createOscillator(); osc.type='triangle'; osc.frequency.value=freqOf(0);
    const gain=AC.createGain(); gain.gain.value=0; osc.connect(gain); gain.connect(AC.destination); osc.start();
    const dgain=AC.createGain(); dgain.gain.value=0; dgain.connect(AC.destination);
    for (const s of [-EDO,0]){ const o=AC.createOscillator(); o.type='sine'; o.frequency.value=freqOf(s); o.connect(dgain); o.start(); }
    live={osc,gain,dgain}; }
  return AC; }
function liveOn(){ ensureAudio(); if (!live) return; const now=AC.currentTime;
  live.gain.gain.cancelScheduledValues(now); live.gain.gain.setTargetAtTime(0.20,now,0.008); live.dgain.gain.setTargetAtTime(0.05,now,0.03); }
function liveSet(step){ if (live&&AC) live.osc.frequency.setTargetAtTime(freqOf(step),AC.currentTime,0.006); }
function liveOff(){ if (!live) return; const now=AC.currentTime; live.gain.gain.setTargetAtTime(0,now,0.03); live.dgain.gain.setTargetAtTime(0,now,0.05); }
// The voice, drone and strums live in core/roll-audio.js so the library page sounds
// a phrase exactly as the draw link it replaces does — same gamaka interpolation,
// same envelopes. draw keeps the transport: the audio module schedules and says when
// it starts, and the playhead below counts from there.
let audio=null;
function rollAudio(){ const a=ensureAudio(); if (!a) return null; if (!audio){ audio=createRollAudio(a, freqOf); audio.setMix({ drone:droneVol, tala:talaVol }); } return audio; }
function stopPlayback(){ playing=false; playPos=null; if (rafId){ cancelAnimationFrame(rafId); rafId=0; }
  if (audio) audio.stop();
  if (mode==='roll') render(); }
// playhead loop — advance a line down the roll and scroll so it stays in view ("rolls up")
function tick(){ if (!playing||!AC) return; const el=Math.max(0, AC.currentTime-playStart);
  const pos=playFromU + el/secPerUnit();
  if (pos>=playToU){ playing=false; playPos=null; setPlayBtn('▶',playLabel()); render(); return; }
  playPos=pos;
  // Auto-scroll so the playhead stays ~40% down the viewport (virtual coords). Setting
  // scrollTop fires the scroll listener → render(); we also render() to be safe.
  const hd=$('holder'); hd.scrollTop=Math.max(0, Math.min(Math.max(0,virtH()-hd.clientHeight), (PAD.t+pos*pxU())-hd.clientHeight*0.4));
  render();
  rafId=requestAnimationFrame(tick); }
function playLabel(){ const lo=Math.min(markerA,markerB), hi=Math.max(markerA,markerB); return (lo>0.01||hi<TOTAL-0.01) ? 'Play A–B' : 'Play phrase'; }
function playNote(i){ const au=rollAudio(); if (!au) return; stopPlayback();
  au.note(NOTES[i], Math.max(0.5, NOTES[i].dur*secPerUnit())); }
function autoPlay(){ if (sel>=0&&NOTES[sel].curve) playNote(sel); }
// play the roll from `from` to `to` length-units (partial notes at the ends sound their portion)
function playFrom(from,to){ const au=rollAudio(); if (!au) return; from=Math.max(0,from); to=Math.min(TOTAL,to); if (to<=from) return;
  stopPlayback();
  const start=au.phrase({ notes:NOTES, starts, from, to, secPerUnit:secPerUnit(),
    tala:{ measure:talaMeasure, accents:talaAccents } });
  playing=true; paused=false; playStart=start; playFromU=from; playToU=to; playPos=from;
  setPlayBtn('⏸','Pause'); if (rafId) cancelAnimationFrame(rafId); rafId=requestAnimationFrame(tick); }
function pausePlayback(){ if (!playing) return; pausedAt=playPos; pausedTo=playToU; stopPlayback(); paused=true; playPos=pausedAt; setPlayBtn('▶','Resume'); render(); }
function segRange(){ return [Math.min(markerA,markerB), Math.max(markerA,markerB)]; }
$('play').onclick=()=>{ if (mode==='draw'){ playNote(sel); return; }
  if (playing){ pausePlayback(); return; }
  if (paused){ playFrom(pausedAt,pausedTo); return; }
  const [lo,hi]=segRange(); playFrom(lo,hi); };
$('stop').onclick=()=>{ stopPlayback(); paused=false; playPos=null; setPlayBtn('▶',playLabel()); if (mode==='roll') render(); };
// Back to the start of what Play would play -- marker A when a segment is set, the
// top of the piece otherwise. Distinct from Stop, which ends playback and takes the
// playhead off the roll entirely: rewinding PARKS the playhead at the start, so you
// can see where the next Play begins.
//
// It has to clear `paused`. Pause remembers where it stopped and Play resumes there,
// so rewinding a paused piece without clearing it would move the playhead to the top
// and then resume from the middle anyway -- the one bug this button invites.
$('rewind').onclick=()=>{ const [lo,hi]=segRange();
  if (playing){ stopPlayback(); playFrom(lo,hi); return; }   // restart from the top, still playing
  paused=false; pausedAt=lo; pausedTo=hi; playPos=lo;
  setPlayBtn('▶',playLabel()); if (mode==='roll') render(); };

// ---------- source text (inline gamaka) + share ----------
let shareLink='', shareTimer=null;
// The composition text with the drawn curves inline, each NOTE-RELATIVE (delta).
function inlineSrc(){ const curves={};
  // 2dp on the delta as well as on u -- rounding it to a whole step here would
  // undo the precision detect.js keeps, every time draw re-serialised.
  NOTES.forEach((n)=>{ if (n.curve) curves[n.tok]=n.curve.map(([u,s])=>[Math.round(u*100)/100, Math.round((s-n.step)*100)/100]); });
  return serializeInline(srcText, curves); }

// ---------- model<->srgm edit glue (note-edit core wiring) ----------
// Raga context for step<->swara naming, from the current composition's raga.
function ragaCtx(){ const { ragaSteps, ragaSwaraName } = buildRagaSteps(curRaga || ''); return { useRaga: !!(curRaga && ragaSteps), ragaSteps, ragaSwaraName }; }
// Snapshot of the current model keyed by source-token ordinal (rests excluded).
function modelByTok(){ const m=new Map(); NOTES.forEach(n=>m.set(n.tok,{ step:n.step, dur:n.dur, octave:n.octave, curve:n.curve })); return m; }
// The raga's pitch-classes (single-octave 53-EDO MOD-steps) for pitch snapping.
// IMPORTANT: snapToRagaRow(step, gridSteps) reconstructs the octave from `step`
// itself, so gridSteps must be single-octave mods (0..52), NOT absolute multi-octave
// rows — passing absolute rows would double-count the octave. Raga mode => the
// raga's mod-steps; no-raga (c12) => the distinct pitch-classes of existing notes.
function ragaRowSteps(){ const { ragaSteps }=ragaCtx();
  if (ragaSteps) return [...ragaSteps];
  return [...new Set(NOTES.map(n=>((n.step%EDO)+EDO)%EDO))].sort((a,b)=>a-b); }

// ---- undo (structural edits round-trip through srcText) ----
let undoStack=[];
function pushUndo(){ undoStack.push(srcText); if (undoStack.length>50) undoStack.shift(); }
async function undo(){ hideToast(); if (!undoStack.length) return; const prev=undoStack.pop();
  if (mode==='draw') $('back').click(); buildModel(prev); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
$('undobtn').onclick=()=>{ undo(); };
// Ctrl/Cmd+Z triggers structural undo only in roll mode and only outside the srgm
// editor textarea, so native textarea undo (typing) still works while editing text.
document.addEventListener('keydown', e=>{ if ((e.ctrlKey||e.metaKey) && !e.shiftKey && (e.key==='z'||e.key==='Z') && mode==='roll' && document.activeElement!==$('editor')){ e.preventDefault(); undo(); } });
$('delbtn').onclick=()=>{ deleteSelected(); };
// Del/Backspace, but never while the srgm editor has focus — there the key belongs
// to the text, and deleting a note out from under someone who is typing is the kind
// of thing there is no obvious way back from.
document.addEventListener('keydown', e=>{
  if (e.key!=='Delete' && e.key!=='Backspace') return;
  if (document.activeElement===$('editor')) return;
  const t=document.activeElement; if (t && /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName)) return;
  if (!(selRest>=0 || (sel>=0 && NOTES[sel]))) return;
  e.preventDefault(); deleteSelected();
});

// Re-serialize the current model to srgm, then rebuild everything from that text.
// A rest's new length, written back to its own token.
async function commitRestDur(tok, dur){
  const newSrc=serializeModel(srcText, { model:modelByTok(), changed:new Set(), inserts:new Map(),
    deletes:new Set(), deriveOctave:false, ctx:ragaCtx(), restDurs:new Map([[tok,dur]]) });
  buildModel(newSrc); syncControls(); resizeCanvas(); render(); await rebuildShare();
}
// Delete whatever is selected — a note, or a rest. Removing a note leaves NO silence
// in its place: the piece gets shorter, which is what deleting a note means. Paint a
// rest if a gap is wanted.
async function deleteSelected(){
  const tok = selRest>=0 ? selRest : (sel>=0 && NOTES[sel] ? NOTES[sel].tok : -1);
  if (tok<0) return;
  pushUndo();
  const wasDrawing = mode==='draw';
  selRest=-1; sel=-1;
  // The note being curve-edited is gone, so there is nothing left to edit — go back
  // to the roll rather than leaving the editor pointed at a note that no longer is.
  if (wasDrawing) $('back').click();
  await commitEdit({ deletes:new Set([tok]), deriveOctave:true });
  syncDelete();
}
// The button is only live when something is selected — a delete with no target is
// not a no-op the user can see, it just looks broken.
function syncDelete(){ const b=$('delbtn'); if (!b) return;
  // Also in draw mode: clicking a note OPENS it for curve editing, so that is exactly
  // where someone looking at a note they want rid of will be.
  b.disabled = !(selRest>=0 || (sel>=0 && NOTES[sel]));
}
// A dropped token leaves its separator behind, so every delete widened a gap in the
// saved notation and two adjacent deletes widened it twice. srgm is whitespace-
// separated, so collapsing a run of spaces changes nothing except how it reads —
// except inside a comment, where the spacing is someone's text.
const tidySpaces = (src) => src.split('\n')
  .map((l) => (l.trimStart().startsWith('%') ? l : l.replace(/[ \t]{2,}/g, ' ').replace(/[ \t]+$/, '')))
  .join('\n');
async function commitEdit({ changed=new Set(), inserts=new Map(), deletes=new Set(), deriveOctave=false, restDurs=undefined }){
  let newSrc=serializeModel(srcText, { model:modelByTok(), changed, inserts, deletes, deriveOctave, ctx:ragaCtx(), restDurs });
  if (deletes.size) newSrc=tidySpaces(newSrc);
  buildModel(newSrc); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
// Reflect srcText into the editor textarea — but never clobber the box the user
// is actively typing in (that also preserves its native ctrl-z history).
function syncEditor(){ const t=$('editor'); if (t && document.activeElement!==t) t.value=srcText; }
// A draw changed the curves: regenerate the inline srgm, show it in the editor,
// persist it, and refresh the share link.
// ROUND TRIP: inlineSrc() REWRITES the source to carry the edited curves, and it
// is what gets saved, shared and reloaded. If it emits something the parser
// cannot read back, whatever it mangled is already lost -- so it is read back
// here, where it was written, rather than by whoever opens the link.
// What a share link carries: the notation, plus the mixer levels ONLY when they
// are not the defaults. Otherwise every ordinary link would change shape for a
// setting nobody touched. Both places that build a link go through here — a link
// opened with the tala silenced must not lose that on the first edit, and editing
// is exactly what the other builder runs on.
const shareBody = (src) => (droneVol!==DEFAULT_MIX.dv || talaVol!==DEFAULT_MIX.tv)
  ? JSON.stringify({ v:2, srgm:src, mix:{ dv:droneVol, tv:talaVol } })
  : src;
async function rebuildShare(){ srcText=inlineSrc(); syncEditor();
  try { reportDiagnostics(parse(srcText), true); }
  catch(_){ reportDiagnostics({ diagnostics:[{ message:'the generated notation could not be parsed at all' }] }, true); }
  try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}
  try{ shareLink=location.origin+location.pathname+'#'+await encodeShareToken(shareBody(srcText)); }catch(e){ shareLink=''; } }
function scheduleShare(){ clearTimeout(shareTimer); shareTimer=setTimeout(rebuildShare,150); }
// Editor edits: reparse the srgm the user typed (debounced), rebuild the roll.
let editTimer=null;
async function onEditorInput(){ hideToast(); if (mode==='draw') $('back').click();   // a reparse changes NOTES; leave draw mode so sel can't dangle
  srcText=$('editor').value; buildModel(srcText);
  syncControls(); resizeCanvas(); render();
  try{ localStorage.setItem(LS_KEY, srcText); }catch(_){}
  try{ shareLink=location.origin+location.pathname+'#'+await encodeShareToken(shareBody(srcText)); }catch(e){ shareLink=''; } }
$('share').onclick=()=>{ const url=shareLink; if (!url){ rebuildShare(); return; }
  const b=$('share'), orig=b.textContent, done=m=>{ b.textContent=m; setTimeout(()=>b.textContent=orig,1800); };
  if (navigator.share){ navigator.share({ title:'RagamRoll gamakas', url }).then(()=>done('Shared ✓')).catch(()=>{}); return; }
  if (navigator.clipboard){ navigator.clipboard.writeText(url).then(()=>done('Copied ✓')).catch(()=>window.prompt('Copy this link:',url)); return; }
  window.prompt('Copy this link:', url); };

// ---------- load / boot ----------
// Debug dump: log the note map (index, source token ordinal, swara, curve points).
function logNotes(tag){ try{ console.log(`[draw] ${tag} — idx:tok swara [pts]:`,
  NOTES.map((n,i)=>`${i}:t${n.tok} ${n.swara}${n.octave}${n.curve?` [${n.curve.length}]`:''}`).join('   ')); }catch(_){}
}
// The mixer levels a link can carry. Kept to what a link should be allowed to set
// on someone else's page: how loud the accompaniment is, nothing about the piece.
// Absent keys keep the page's current value, so a link may set one and leave the
// other alone.
const DEFAULT_MIX={ dv:0.5, tv:0.5 };
function applyMix(u){
  if (!u || typeof u!=='object') return;
  const set=(k,v)=>{ if (!(typeof v==='number') || !isFinite(v)) return; const c=Math.max(0,Math.min(1,v));
    if (k==='dv'){ droneVol=c; if ($('dronevol')) $('dronevol').value=String(c); if (audio) audio.setMix({ drone:c }); }
    else { talaVol=c; if ($('talavol')) $('talavol').value=String(c); if (audio) audio.setMix({ tala:c }); } };
  set('dv',u.dv); set('tv',u.tv);
}
// A share hash is pako(srgm text), or pako(JSON {v:2, srgm, mix}) when the link
// carries mixer levels — the /ragas links do, to open with the tala strums at zero:
// those recordings are free-rhythm arohana/avarohana and signature phrases, so
// veena accents on a cycle nobody sang are noise. Legacy links were
// pako(JSON {v,src,g}); detect and convert those once (apply the index-keyed
// curves; they re-emit inline).
function applyShared(decoded){
  hideToast();
  userGridMin = userGridMax = userGridBottom = null;   // new composition: start at auto/seed bounds, not a stale stretch
  let legacy=null, carried=null;
  try{ const o=JSON.parse(decoded);
    if (o&&typeof o.src==='string') legacy=o;
    else if (o&&typeof o.srgm==='string') carried=o; }catch(_){}
  console.log(`[draw] pako decoded — ${legacy?'LEGACY {v,src,g}':carried?'{v:2, srgm, mix}':'raw srgm text'} (${decoded.length} chars):\n%s`,
    legacy||carried ? JSON.stringify(legacy||carried, null, 1) : decoded);
  if (legacy){ buildModel(legacy.src);
    if (legacy.g) for (const k in legacy.g){ const i=+k; if (NOTES[i]) NOTES[i].curve=legacy.g[k].map(p=>[p[0],p[1]]); } }
  else if (carried){ applyMix(carried.mix); buildModel(carried.srgm); }
  else buildModel(decoded);   // raw srgm text; inline gamaka decoded in buildModel
  logNotes('after applyShared');
}
async function loadComposition(){
  const h=location.hash.replace(/^#/,'');
  if (h){ try{ applyShared(await decodeShareToken(h)); return; }catch(e){ console.warn('[draw] pako decode failed', e); } }
  const ls=localStorage.getItem(LS_KEY) || 'Raga=hamsadhwani,0 O=5 L=1 S R G P N >S';
  console.log(`[draw] loaded from localStorage (${ls.length} chars):\n%s`, ls);
  buildModel(ls); logNotes('after localStorage load');
}
// ---------- composition I/O: Open (examples / file / link), Save, Export MIDI ----------
const baseName = s => String(s||'ragamroll').replace(/^.*[\/\\]/,'').replace(/\.[^.]+$/,'') || 'ragamroll';
// Load a whole new composition into the roll + editor (and persist / reshare).
async function loadSrc(text, name){ hideToast(); if (mode==='draw') $('back').click(); stopPlayback();
  userGridMin = userGridMax = userGridBottom = null;   // new composition: start at auto/seed bounds, not a stale stretch
  if (name) docName=name; buildModel(text); syncControls(); resizeCanvas(); render(); await rebuildShare(); }
async function pasteLink(){ const inp=window.prompt('Paste a RagamRoll share link or pako token:'); if (!inp) return;
  const m=/pako:[A-Za-z0-9\-_]+/.exec(inp); const tok=m?m[0]:inp.trim().replace(/^#/,'');
  try{ if (mode==='draw') $('back').click(); stopPlayback(); applyShared(await decodeShareToken(tok));
    syncControls(); resizeCanvas(); render(); await rebuildShare(); }
  catch(e){ window.alert('That isn’t a valid RagamRoll link — it should contain a pako: token.'); } }
// Open ▾ menu (examples list + open file + paste link)
function hideOpen(){ $('openmenu').style.display='none'; }
$('openbtn').onclick=e=>{ e.stopPropagation(); const m=$('openmenu');
  if (m.style.display==='block'){ hideOpen(); return; }
  m.style.display='block'; const r=$('openbtn').getBoundingClientRect();
  m.style.left=Math.max(6, Math.min(r.left, innerWidth-m.offsetWidth-8))+'px';
  m.style.top=Math.max(6, r.top-m.offsetHeight-6)+'px'; };
document.addEventListener('pointerdown', e=>{ const m=$('openmenu'); if (m.style.display==='block' && !m.contains(e.target) && e.target!==$('openbtn')) hideOpen(); });
$('exsel').onchange=async e=>{ const name=e.target.value; e.target.value=''; if (!name) return; hideOpen();
  try{ loadSrc(await fetch('./examples/'+name+'.srgm').then(r=>{ if(!r.ok) throw 0; return r.text(); }), name); }
  catch(_){ window.alert('Could not load that example.'); } };
$('openmenu').addEventListener('click', e=>{ const act=e.target.getAttribute('data-act'); if (!act) return; hideOpen();
  if (act==='new'){ loadSrc(blankSrc(), 'untitled'); setEditorH(Math.round((window.innerHeight||600)*0.35)); }
  else if (act==='file') $('fileinput').click(); else if (act==='link') pasteLink(); });
$('fileinput').onchange=async e=>{ const f=e.target.files[0]; e.target.value=''; if (f) loadSrc(await f.text(), baseName(f.name)); };
// Save / Export MIDI (gamakas are audio-only; MIDI stays plain)
function download(name, data, type){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([data],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
$('save').onclick=()=>download(docName+'.srgm', srcText, 'text/plain');
$('exportmidi').onclick=()=>{ try{ download(docName+'.mid', writeSMF(buildSequence(parse(srcText))), 'audio/midi'); }catch(e){ window.alert('MIDI export failed: '+e.message); } };
window.__rr = { notes:()=>NOTES, rests:()=>RESTS.map(r=>({...r})), get selRest(){ return selRest; },
  intents:()=>INTENT_LOG.map(i=>({...i})), clearIntents:()=>{ INTENT_LOG.length=0; }, get mode(){ return mode; },
  get delEnabled(){ return !$('delbtn').disabled; }, restEdgeY:(tok)=>{ const r=RESTS.find(x=>x.tok===tok); return r?Y(r.t0+r.dur):null; },
  restMidY:(tok)=>{ const r=RESTS.find(x=>x.tok===tok); return r?Y(r.t0+r.dur/2):null; }, X, Y, starts:()=>starts, get playing(){ return playing; }, get paused(){ return paused; }, get stepMin(){ return stepMin; }, get stepMax(){ return stepMax; }, get padTop(){ return PAD.t; }, gridSteps:()=>gridPitches.map(g=>g.step), labelChipW:()=>14, get shareLink(){ return shareLink; }, get playPos(){ return playPos; }, get markerA(){ return markerA; }, get markerB(){ return markerB; }, get talaMeasure(){ return talaMeasure; }, get talaAccents(){ return talaAccents; }, get droneVol(){ return droneVol; }, get talaVol(){ return talaVol; }, inlineSrc:()=>inlineSrc(), rebuild:()=>rebuildShare(), get src(){ return srcText; } };
// Populate the examples dropdown from the manifest (same source as the app).
fetch('./examples/index.json').then(r=>r.json()).then(list=>{
  const sel=$('exsel'); for (const n of list){ const o=document.createElement('option'); o.value=n; o.textContent=n; sel.appendChild(o); }
}).catch(()=>{});
Promise.all([
  fetch('./core/raga-db.json').then(r=>r.json()),   // one database: scale + mela + shrutis + arohana, aliases folded in
]).then(([db])=>{ const ragas=db; setRagas(db); setRagaExt(db);
    const ragaNames=Object.keys(ragas).filter(n=>!/^mela_\d+$/i.test(n)).sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase())); defaultRaga=ragaNames[0]||'c12';
    const rl=$('ragalist'); for (const n of ragaNames){ const o=document.createElement('option'); o.value=n; rl.appendChild(o); }
    const ts=$('talasel'); for (const n of Object.keys(TALA_MAP)){ const o=document.createElement('option'); o.value=n; o.textContent=n; ts.appendChild(o); }
    return loadComposition(); })
  .then(()=>{ window.addEventListener('resize',fit); if (window.visualViewport) window.visualViewport.addEventListener('resize',fit);
    window.addEventListener('orientationchange',()=>setTimeout(fit,200));
    new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
    if (!NOTES.length) $('mode').textContent='no notes — open a composition in the app first';
    syncControls(); fit(); resizeCanvas(); rebuildShare(); });
